#!/bin/bash
sed -i 's/        viewModelScope.launch {\n            securityPreferences.incognitoMode().changes().collectLatest {\n                _feedScreenState.update { state -> state.copy(incognitoMode = it) }\n            }\n        }/        securityPreferences.incognitoMode().changes()\n            .distinctUntilChanged()\n            .onEach { _feedScreenState.update { state -> state.copy(incognitoMode = it) } }\n            .launchIn(viewModelScope)/' app/src/main/java/eu/kanade/tachiyomi/ui/feed/FeedViewModel.kt

sed -i 's/        viewModelScope.launch {\n            preferences.downloadOnlyOverUnmetered().changes().collectLatest {\n                _feedScreenState.update { state -> state.copy(downloadOnlyOnUnmetered = it) }\n            }\n        }/        preferences.downloadOnlyOverUnmetered().changes()\n            .distinctUntilChanged()\n            .onEach { _feedScreenState.update { state -> state.copy(downloadOnlyOnUnmetered = it) } }\n            .launchIn(viewModelScope)/' app/src/main/java/eu/kanade/tachiyomi/ui/feed/FeedViewModel.kt

sed -i 's/        viewModelScope.launch {\n            preferences.feedViewOutlineCards().changes().collectLatest {\n                _feedScreenState.update { state -> state.copy(outlineCards = it) }\n            }\n        }/        preferences.feedViewOutlineCards().changes()\n            .distinctUntilChanged()\n            .onEach { _feedScreenState.update { state -> state.copy(outlineCards = it) } }\n            .launchIn(viewModelScope)/' app/src/main/java/eu/kanade/tachiyomi/ui/feed/FeedViewModel.kt

sed -i 's/        viewModelScope.launch {\n            libraryPreferences.outlineOnCovers().changes().collectLatest {\n                _feedScreenState.update { state -> state.copy(outlineCovers = it) }\n            }\n        }/        libraryPreferences.outlineOnCovers().changes()\n            .distinctUntilChanged()\n            .onEach { _feedScreenState.update { state -> state.copy(outlineCovers = it) } }\n            .launchIn(viewModelScope)/' app/src/main/java/eu/kanade/tachiyomi/ui/feed/FeedViewModel.kt

sed -i 's/        viewModelScope.launch {\n            preferences.groupChaptersUpdates().changes().collectLatest {\n                _feedScreenState.update { state -> state.copy(groupUpdateChapters = it) }\n            }\n        }/        preferences.groupChaptersUpdates().changes()\n            .distinctUntilChanged()\n            .onEach { _feedScreenState.update { state -> state.copy(groupUpdateChapters = it) } }\n            .launchIn(viewModelScope)/' app/src/main/java/eu/kanade/tachiyomi/ui/feed/FeedViewModel.kt

sed -i '1s/^/import kotlinx.coroutines.flow.onEach\nimport kotlinx.coroutines.flow.launchIn\nimport kotlinx.coroutines.flow.distinctUntilChanged\n/' app/src/main/java/eu/kanade/tachiyomi/ui/feed/FeedViewModel.kt
