package eu.kanade.tachiyomi.source.online.utils

enum class MdLang(val lang: String, val dexLang: String, val langId: Int) {
    English("en", "gb", 1),
    Japanese("ja", "jp", 2),
    Polish("pl", "pl", 3),
    SerboCroatian("sh", "rs", 4),
    Dutch("nl", "nl", 5),
    Italian("it", "it", 6),
    Russian("ru", "ru", 7),
    German("de", "de", 8),
    Hungarian("hu", "hu", 9),
    French("fr", "fr", 10),
    Finnish("fi", "fi", 11),
    Vietnamese("vi", "vn", 12),
    Greek("el", "gr", 13),
    Bulgarian("bg", "bg", 14),
    Spanish("es", "es", 15),
    PortugeseBrazilian("pt-BR", "br", 16),
    Portuguese("pt", "pt", 17),
    Swedish("sv", "se", 18),
    Arabic("ar", "sa", 19),
    Danish("da", "dk", 20),
    ChineseSimplifed("zh-Hans", "cn", 21),
    Bengali("bn", "bd", 22),
    Romanian("ro", "ro", 23),
    Czech("cs", "cz", 24),
    Mongolian("mn", "mn", 25),
    Turkish("tr", "tr", 26),
    Indonesian("id", "id", 27),
    Korean("ko", "kr", 28),
    SpanishLATAM("es-419", "mx", 29),
    Persian("fa", "ir", 30),
    Malay("ms", "my", 31),
    Thai("th", "th", 32),
    Catalan("ca", "ct", 33),
    Filipino("fil", "ph", 34),
    ChineseTraditional("zh-Hant", "hk", 35),
    Ukrainian("uk", "ua", 36),
    Burmese("my", "mm", 37),
    Hebrew("lt", "il", 38),
    Hindi("lt", "in", 39),
    Other("lt", " ", 40),
    Norwegian("lt", "no", 41)
}