blank_issues_enabled: false
contact_links:
  about: For more immediate support feel free to join the discord channel
  url: https://tachiyomi.org/docs/guides/troubleshooting/
  about: Guides, troubleshooting, and answers to common questions
