name: 🐞 Issue report
description: Report an issue or bug in Neko
labels: [ bug ]
body:

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
      description: Provide an example of the issue.
      placeholder: |
        Example:
          1. First step
          2. Second step
          3. Issue here
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Explain what you should expect to happen.
      placeholder: |
        Example:
          "This should happen..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: Explain what actually happens.
      placeholder: |
        Example:
          "This happened instead..."
    validations:
      required: true

  - type: textarea
    id: crash-logs
    attributes:
      label: Crash logs
      description: |
        If you're experiencing crashes, share the crash logs from **More → Settings → Advanced** then press **Dump crash logs**.
      placeholder: |
        You can paste the crash logs in pure text or upload it as an attachment.

  - type: input
    id: tachiyomi-version
    attributes:
      label: Neko version
      description: You can find your Neko version in **More → About**.
      placeholder: |
        Example: "2.8.0.2"
    validations:
      required: true

  - type: input
    id: android-version
    attributes:
      label: Android version
      description: You can find this somewhere in your Android settings.
      placeholder: |
        Example: "Android 12"
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device
      description: List your device and model.
      placeholder: |
        Example: "Google Pixel 6"
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Read this carefully, we will close and ignore your issue if you skimmed through this.
      options:
        - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
          required: true
        - label: I have written a short but informative title.
        - label: I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
          required: true
        - label: I have filled out all of the requested information in this form.
          required: true
