package org.nekomanga.presentation.theme.colorschemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object BlueColorScheme : BaseColorScheme() {
    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFF0057E3),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFB8C5FF),
            onPrimaryContainer = Color(0xFF00174F),
            inversePrimary = Color(0xFFB8C5FF),
            secondary = Color(0xFF5A5D72),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFE0E1FF),
            onSecondaryContainer = Color(0xFF171A2C),
            tertiary = Color(0xFF735660),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFFFDAE3),
            onTertiaryContainer = Color(0xFF2B141C),
            background = Color(0xFFFEFBFF),
            onBackground = Color(0xFF1B1B1F),
            surface = Color(0xFFFEFBFF),
            onSurface = Color(0xFF1B1B1F),
            surfaceVariant = Color(0xFFE1E2EC),
            onSurfaceVariant = Color(0xFF44474F),
            surfaceTint = Color(0xFF0057E3),
            inverseSurface = Color(0xFF303033),
            inverseOnSurface = Color(0xFFF2F0F4),
            outline = Color(0xFF74777F),
            outlineVariant = Color(0xFFC4C6D0),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFFFEFBFF),
            surfaceDim = Color(0xFFDCDFE4),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF7F7FA),
            surfaceContainer = Color(0xFFF2F2F5),
            surfaceContainerHigh = Color(0xFFECEEF0),
            surfaceContainerHighest = Color(0xFFE6E8EB),
            primaryFixed = Color(0xFFB8C5FF),
            primaryFixedDim = Color(0xFF9EAFFF),
            onPrimaryFixed = Color(0xFF00174F),
            onPrimaryFixedVariant = Color(0xFF0043B0),
            secondaryFixed = Color(0xFFE0E1FF),
            secondaryFixedDim = Color(0xFFC4C5DD),
            onSecondaryFixed = Color(0xFF171A2C),
            onSecondaryFixedVariant = Color(0xFF434659),
            tertiaryFixed = Color(0xFFFFDAE3),
            tertiaryFixedDim = Color(0xFFE0BDC6),
            onTertiaryFixed = Color(0xFF2B141C),
            onTertiaryFixedVariant = Color(0xFF593E48),
        )
    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFFB8C5FF),
            onPrimary = Color(0xFF00297B),
            primaryContainer = Color(0xFF0040B4),
            onPrimaryContainer = Color(0xFFDCE3FF),
            inversePrimary = Color(0xFF0057E3),
            secondary = Color(0xFFC4C5DD),
            onSecondary = Color(0xFF2D2F42),
            secondaryContainer = Color(0xFF434659),
            onSecondaryContainer = Color(0xFFE0E1FF),
            tertiary = Color(0xFFE0BDC6),
            onTertiary = Color(0xFF422A31),
            tertiaryContainer = Color(0xFF594048),
            onTertiaryContainer = Color(0xFFFFDAE3),
            background = Color(0xFF1B1B1F),
            onBackground = Color(0xFFE4E2E6),
            surface = Color(0xFF1B1B1F),
            onSurface = Color(0xFFE4E2E6),
            surfaceVariant = Color(0xFF44474F),
            onSurfaceVariant = Color(0xFFC4C6D0),
            surfaceTint = Color(0xFFB8C5FF),
            inverseSurface = Color(0xFFE4E2E6),
            inverseOnSurface = Color(0xFF1B1B1F),
            outline = Color(0xFF8E9099),
            outlineVariant = Color(0xFF44474F),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFF44474F),
            surfaceDim = Color(0xFF1B1B1F),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            surfaceContainerLowest = Color(0xFF131317),
            surfaceContainerLow = Color(0xFF1F1E23),
            surfaceContainer = Color(0xFF232227),
            surfaceContainerHigh = Color(0xFF2D2C31),
            surfaceContainerHighest = Color(0xFF38363C),
            primaryFixed = Color(0xFFB8C5FF),
            primaryFixedDim = Color(0xFF9EAFFF),
            onPrimaryFixed = Color(0xFF00174F),
            onPrimaryFixedVariant = Color(0xFF0043B0),
            secondaryFixed = Color(0xFFE0E1FF),
            secondaryFixedDim = Color(0xFFC4C5DD),
            onSecondaryFixed = Color(0xFF171A2C),
            onSecondaryFixedVariant = Color(0xFF434659),
            tertiaryFixed = Color(0xFFFFDAE3),
            tertiaryFixedDim = Color(0xFFE0BDC6),
            onTertiaryFixed = Color(0xFF2B141C),
            onTertiaryFixedVariant = Color(0xFF593E48),
        )
}
