package org.nekomanga.presentation.theme.colorschemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object BlueColorScheme : BaseColorScheme() {
    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFF0066FF),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFD3E5FF),
            onPrimaryContainer = Color(0xFF003D99),
            inversePrimary = Color(0xFF99CCFF),
            secondary = Color(0xFF00C7FF),
            onSecondary = Color(0xFF000000),
            secondaryContainer = Color(0xFFE5FFFF),
            onSecondaryContainer = Color(0xFF003D4D),
            tertiary = Color(0xFFFF6600),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFFFD9B3),
            onTertiaryContainer = Color(0xFF662900),
            background = Color(0xFFFFFCF5),
            onBackground = Color(0xFF1F1E1A),
            surface = Color(0xFFFFFCF5),
            onSurface = Color(0xFF1F1E1A),
            surfaceVariant = Color(0xFFE0E0D8),
            onSurfaceVariant = Color(0xFF55554D),
            surfaceTint = Color(0xFF0066FF),
            inverseSurface = Color(0xFF333333),
            inverseOnSurface = Color(0xFFF0F0F0),
            outline = Color(0xFF999999),
            outlineVariant = Color(0xFFC0C0C0),
            scrim = Color(0xFF000000),
            error = Color(0xFFCC3333),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFD6D6),
            onErrorContainer = Color(0xFF4D0000),
            surfaceBright = Color(0xFFFFFFFF),
            surfaceDim = Color(0xFFF0F0E8),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF7F7F0),
            surfaceContainer = Color(0xFFEDEDE4),
            surfaceContainerHigh = Color(0xFFE3E3DC),
            surfaceContainerHighest = Color(0xFFD9D9D3),
            primaryFixed = Color(0xFFB3CCFF),
            primaryFixedDim = Color(0xFF99B3FF),
            onPrimaryFixed = Color(0xFF001A4D),
            onPrimaryFixedVariant = Color(0xFF0040B3),
            secondaryFixed = Color(0xFFE5FFFF),
            secondaryFixedDim = Color(0xFFCCFFFF),
            onSecondaryFixed = Color(0xFF002933),
            onSecondaryFixedVariant = Color(0xFF006B80),
            tertiaryFixed = Color(0xFFFFD9B3),
            tertiaryFixedDim = Color(0xFFFFC080),
            onTertiaryFixed = Color(0xFF4D1A00),
            onTertiaryFixedVariant = Color(0xFFB34D00),
        )

    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFF99CCFF),
            onPrimary = Color(0xFF003366),
            primaryContainer = Color(0xFF004C99),
            onPrimaryContainer = Color(0xFFCCEEFF),
            inversePrimary = Color(0xFF0066FF),
            secondary = Color(0xFF66FFFF),
            onSecondary = Color(0xFF003333),
            secondaryContainer = Color(0xFF004C66),
            onSecondaryContainer = Color(0xFFCCFFFF),
            tertiary = Color(0xFFFFB380),
            onTertiary = Color(0xFF663300),
            tertiaryContainer = Color(0xFF994C00),
            onTertiaryContainer = Color(0xFFFFD9B3),
            background = Color(0xFF1A1A1A),
            onBackground = Color(0xFFE8E8E8),
            surface = Color(0xFF1A1A1A),
            onSurface = Color(0xFFE8E8E8),
            surfaceVariant = Color(0xFF404040),
            onSurfaceVariant = Color(0xFFC0C0C0),
            surfaceTint = Color(0xFF99CCFF),
            inverseSurface = Color(0xFFE8E8E8),
            inverseOnSurface = Color(0xFF1A1A1A),
            outline = Color(0xFF808080),
            outlineVariant = Color(0xFF404040),
            scrim = Color(0xFF000000),
            error = Color(0xFFFF9999),
            onError = Color(0xFF4D0000),
            errorContainer = Color(0xFF800000),
            onErrorContainer = Color(0xFFFFD6D6),
            surfaceBright = Color(0xFF404040),
            surfaceDim = Color(0xFF1A1A1A),
            surfaceContainerLowest = Color(0xFF0D0D0D),
            surfaceContainerLow = Color(0xFF262626),
            surfaceContainer = Color(0xFF333333),
            surfaceContainerHigh = Color(0xFF474747),
            surfaceContainerHighest = Color(0xFF5C5C5C),
            primaryFixed = Color(0xFFB3CCFF),
            primaryFixedDim = Color(0xFF99B3FF),
            onPrimaryFixed = Color(0xFF001A4D),
            onPrimaryFixedVariant = Color(0xFF0040B3),
            secondaryFixed = Color(0xFFE5FFFF),
            secondaryFixedDim = Color(0xFFCCFFFF),
            onSecondaryFixed = Color(0xFF002933),
            onSecondaryFixedVariant = Color(0xFF004C66),
            tertiaryFixed = Color(0xFFFFD9B3),
            tertiaryFixedDim = Color(0xFFFFC080),
            onTertiaryFixed = Color(0xFF4D1A00),
            onTertiaryFixedVariant = Color(0xFF994C00),
        )
}
