package org.nekomanga.presentation.theme.colorschemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object BlueGreenColorScheme : BaseColorScheme() {
    // Generated using MaterialKolor Builder version 1.2.1 (103)
    // https://materialkolor.com/?color_seed=FF5F9C96&dark_mode=false&style=Expressive&color_spec=SPEC_2025&package_name=com.example.app&expressive=true
    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFF296963),
            onPrimary = Color(0xFFE1FFFB),
            primaryContainer = Color(0xFFAAE9E2),
            onPrimaryContainer = Color(0xFF135853),
            inversePrimary = Color(0xFFBDFDF6),
            secondary = Color(0xFF6F5D2F),
            onSecondary = Color(0xFFFFF8EF),
            secondaryContainer = Color(0xFFF9E0A6),
            onSecondaryContainer = Color(0xFF615023),
            tertiary = Color(0xFF7A5A00),
            onTertiary = Color(0xFFFFF8F1),
            tertiaryContainer = Color(0xFFFDC74F),
            onTertiaryContainer = Color(0xFF5B4100),
            background = Color(0xFFE4FFFF),
            onBackground = Color(0xFF00393B),
            surface = Color(0xFFE4FFFF),
            onSurface = Color(0xFF00393B),
            surfaceVariant = Color(0xFFB0EDEF),
            onSurfaceVariant = Color(0xFF2A686A),
            surfaceTint = Color(0xFF296963),
            inverseSurface = Color(0xFF001112),
            inverseOnSurface = Color(0xFF84A3A3),
            error = Color(0xFFAC3434),
            onError = Color(0xFFFFF7F6),
            errorContainer = Color(0xFFF56965),
            onErrorContainer = Color(0xFF65000B),
            outline = Color(0xFF488486),
            outlineVariant = Color(0xFF80BCBE),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFFE4FFFF),
            surfaceContainer = Color(0xFFC8F7F8),
            surfaceContainerHigh = Color(0xFFBCF2F4),
            surfaceContainerHighest = Color(0xFFB0EDEF),
            surfaceContainerLow = Color(0xFFD4FBFC),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceDim = Color(0xFFA1E6E8),
            primaryFixed = Color(0xFFAAE9E2),
            primaryFixedDim = Color(0xFF9CDAD4),
            onPrimaryFixed = Color(0xFF004440),
            onPrimaryFixedVariant = Color(0xFF21615C),
            secondaryFixed = Color(0xFFF9E0A6),
            secondaryFixedDim = Color(0xFFEBD299),
            onSecondaryFixed = Color(0xFF4D3D12),
            onSecondaryFixedVariant = Color(0xFF6B5A2C),
            tertiaryFixed = Color(0xFFFDC74F),
            tertiaryFixedDim = Color(0xFFEDB943),
            onTertiaryFixed = Color(0xFF422F00),
            onTertiaryFixedVariant = Color(0xFF664A00),
        )
    // Generated using MaterialKolor Builder version 1.2.1 (103)
    // https://materialkolor.com/?color_seed=FF80B8D1&color_primary=FF80B8D1&color_neutral=FF14191B&color_neutralvariant=FF1D2528&dark_mode=true&color_spec=SPEC_2025&package_name=com.example.app&expressive=true
    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFF96CEE8),
            onPrimary = Color(0xFF00465A),
            primaryContainer = Color(0xFF1A596F),
            onPrimaryContainer = Color(0xFFBEEAFF),
            inversePrimary = Color(0xFF2A667C),
            secondary = Color(0xFFB4CAD5),
            onSecondary = Color(0xFF2E434C),
            secondaryContainer = Color(0xFF2A3E47),
            onSecondaryContainer = Color(0xFFADC3CE),
            tertiary = Color(0xFFD4DFFF),
            onTertiary = Color(0xFF3F5074),
            tertiaryContainer = Color(0xFFC0D1FD),
            onTertiaryContainer = Color(0xFF36476B),
            background = Color(0xFF0A0F11),
            onBackground = Color(0xFFDCE7EC),
            surface = Color(0xFF0A0F11),
            onSurface = Color(0xFFDCE7EC),
            surfaceVariant = Color(0xFF1D272B),
            onSurfaceVariant = Color(0xFF8A959A),
            surfaceTint = Color(0xFF96CEE8),
            inverseSurface = Color(0xFFF6FAFC),
            inverseOnSurface = Color(0xFF515658),
            error = Color(0xFFFA746F),
            onError = Color(0xFF490006),
            errorContainer = Color(0xFF871F21),
            onErrorContainer = Color(0xFFFF9993),
            outline = Color(0xFF6C777C),
            outlineVariant = Color(0xFF3F4A4E),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFF232E32),
            surfaceContainer = Color(0xFF131B1E),
            surfaceContainerHigh = Color(0xFF182124),
            surfaceContainerHighest = Color(0xFF1D272B),
            surfaceContainerLow = Color(0xFF0E1417),
            surfaceContainerLowest = Color(0xFF000000),
            surfaceDim = Color(0xFF0A0F11),
            primaryFixed = Color(0xFFA1DAF4),
            primaryFixedDim = Color(0xFF93CCE5),
            onPrimaryFixed = Color(0xFF00394A),
            onPrimaryFixedVariant = Color(0xFF17576D),
            secondaryFixed = Color(0xFFD0E6F2),
            secondaryFixedDim = Color(0xFFC2D8E3),
            onSecondaryFixed = Color(0xFF2E424C),
            onSecondaryFixedVariant = Color(0xFF4A5F68),
            tertiaryFixed = Color(0xFFC0D1FD),
            tertiaryFixedDim = Color(0xFFB3C3EE),
            onTertiaryFixed = Color(0xFF233457),
            onTertiaryFixedVariant = Color(0xFF405075),
        )
}
