package org.nekomanga.presentation.theme.colorschemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object BrownColorScheme : BaseColorScheme() {
    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFF674840),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFFFDAD4),
            onPrimaryContainer = Color(0xFF230704),
            inversePrimary = Color(0xFFECB8B4),
            secondary = Color(0xFFB72D43),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFFFDAD9),
            onSecondaryContainer = Color(0xFF400010),
            tertiary = Color(0xFF675F51),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFEDE4DB),
            onTertiaryContainer = Color(0xFF221C11),
            background = Color(0xFFFFFBFF),
            onBackground = Color(0xFF1D1B1A),
            surface = Color(0xFFFFFBFF),
            onSurface = Color(0xFF1D1B1A),
            surfaceVariant = Color(0xFFF5DDDA),
            onSurfaceVariant = Color(0xFF524442),
            surfaceTint = Color(0xFF674840),
            inverseSurface = Color(0xFF32302F),
            inverseOnSurface = Color(0xFFF6EFEF),
            outline = Color(0xFF857370),
            outlineVariant = Color(0xFFD8C2BF),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFFFFFBFF),
            surfaceDim = Color(0xFFDCD2D0),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFFBF4F3),
            surfaceContainer = Color(0xFFF6EFEF),
            surfaceContainerHigh = Color(0xFFF1EAE9),
            surfaceContainerHighest = Color(0xFFECE4E3),
            primaryFixed = Color(0xFFFFDAD4),
            primaryFixedDim = Color(0xFFECB8B4),
            onPrimaryFixed = Color(0xFF230704),
            onPrimaryFixedVariant = Color(0xFF4F322B),
            secondaryFixed = Color(0xFFFFDAD9),
            secondaryFixedDim = Color(0xFFFFB3B3),
            onSecondaryFixed = Color(0xFF400010),
            onSecondaryFixedVariant = Color(0xFF8E0627),
            tertiaryFixed = Color(0xFFEDE4DB),
            tertiaryFixedDim = Color(0xFFD0C8B8),
            onTertiaryFixed = Color(0xFF221C11),
            onTertiaryFixedVariant = Color(0xFF504639),
        )

    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFFECB8B4),
            onPrimary = Color(0xFF3A1A17),
            primaryContainer = Color(0xFF50312B),
            onPrimaryContainer = Color(0xFFFFDAD4),
            inversePrimary = Color(0xFF674840),
            secondary = Color(0xFFFF8B9C),
            onSecondary = Color(0xFF67001C),
            secondaryContainer = Color(0xFF8E0627),
            onSecondaryContainer = Color(0xFFFFDAD9),
            tertiary = Color(0xFFD0C8B8),
            onTertiary = Color(0xFF383125),
            tertiaryContainer = Color(0xFF4F483A),
            onTertiaryContainer = Color(0xFFEDE4DB),
            background = Color(0xFF2A2220),
            onBackground = Color(0xFFFBECEB),
            surface = Color(0xFF2A2220),
            onSurface = Color(0xFFFBECEB),
            surfaceVariant = Color(0xFF5C4F4B),
            onSurfaceVariant = Color(0xFFD7C1C1),
            surfaceTint = Color(0xFFECB8B4),
            inverseSurface = Color(0xFFFBECEB),
            inverseOnSurface = Color(0xFF2A2220),
            outline = Color(0xFF9F8D8D),
            outlineVariant = Color(0xFF5C4F4B),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFF5C4F4B),
            surfaceDim = Color(0xFF2A2220),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            surfaceContainerLowest = Color(0xFF1F1816),
            surfaceContainerLow = Color(0xFF302725),
            surfaceContainer = Color(0xFF372D2B),
            surfaceContainerHigh = Color(0xFF433936),
            surfaceContainerHighest = Color(0xFF4E433F),
            primaryFixed = Color(0xFFFFDAD4),
            primaryFixedDim = Color(0xFFECB8B4),
            onPrimaryFixed = Color(0xFF230704),
            onPrimaryFixedVariant = Color(0xFF4F322B),
            secondaryFixed = Color(0xFFFFDAD9),
            secondaryFixedDim = Color(0xFFFFB3B3),
            onSecondaryFixed = Color(0xFF400010),
            onSecondaryFixedVariant = Color(0xFF8E0627),
            tertiaryFixed = Color(0xFFEDE4DB),
            tertiaryFixedDim = Color(0xFFD0C8B8),
            onTertiaryFixed = Color(0xFF221C11),
            onTertiaryFixedVariant = Color(0xFF504639),
        )
}
