package org.nekomanga.presentation.theme.colorschemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object GreenColorScheme : BaseColorScheme() {
    // Generated using MaterialKolor Builder version 1.2.1 (103)
    // https://materialkolor.com/?color_seed=FF57BD79&dark_mode=false&style=Expressive&color_spec=SPEC_2025&package_name=com.example.app&expressive=true
    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFF006E39),
            onPrimary = Color(0xFFE8FFE9),
            primaryContainer = Color(0xFF91F8AE),
            onPrimaryContainer = Color(0xFF005F30),
            inversePrimary = Color(0xFF97FEB3),
            secondary = Color(0xFF7F5638),
            onSecondary = Color(0xFFFFF7F4),
            secondaryContainer = Color(0xFFFFDCC5),
            onSecondaryContainer = Color(0xFF70492C),
            tertiary = Color(0xFF97490D),
            onTertiary = Color(0xFFFFF7F5),
            tertiaryContainer = Color(0xFFFFA268),
            onTertiaryContainer = Color(0xFF5C2800),
            background = Color(0xFFE8FFEF),
            onBackground = Color(0xFF013B26),
            surface = Color(0xFFE8FFEF),
            onSurface = Color(0xFF013B26),
            surfaceVariant = Color(0xFFB9EFD0),
            onSurfaceVariant = Color(0xFF376951),
            surfaceTint = Color(0xFF006E39),
            inverseSurface = Color(0xFF001209),
            inverseOnSurface = Color(0xFF88A393),
            error = Color(0xFFAC3434),
            onError = Color(0xFFFFF7F6),
            errorContainer = Color(0xFFF56965),
            onErrorContainer = Color(0xFF65000B),
            outline = Color(0xFF53856C),
            outlineVariant = Color(0xFF89BDA1),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFFE8FFEF),
            surfaceContainer = Color(0xFFCEF7DF),
            surfaceContainerHigh = Color(0xFFC3F3D8),
            surfaceContainerHighest = Color(0xFFB9EFD0),
            surfaceContainerLow = Color(0xFFD8FCE6),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceDim = Color(0xFFABE7C6),
            primaryFixed = Color(0xFF91F8AE),
            primaryFixedDim = Color(0xFF83EAA1),
            onPrimaryFixed = Color(0xFF004A24),
            onPrimaryFixedVariant = Color(0xFF006A36),
            secondaryFixed = Color(0xFFFFDCC5),
            secondaryFixedDim = Color(0xFFFFCAA5),
            onSecondaryFixed = Color(0xFF5A371C),
            onSecondaryFixedVariant = Color(0xFF7B5235),
            tertiaryFixed = Color(0xFFFFA268),
            tertiaryFixedDim = Color(0xFFF59353),
            onTertiaryFixed = Color(0xFF3A1600),
            onTertiaryFixedVariant = Color(0xFF692F00),
        )

    // Generated using MaterialKolor Builder version 1.2.1 (103)
    // https://materialkolor.com/?color_seed=FF5EE14A&color_tertiary=FF654321&dark_mode=true&style=Rainbow&color_spec=SPEC_2025&package_name=com.example.app&expressive=true
    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFF78FC61),
            onPrimary = Color(0xFF025E00),
            primaryContainer = Color(0xFF32B924),
            onPrimaryContainer = Color(0xFF012A00),
            inversePrimary = Color(0xFF036F00),
            secondary = Color(0xFFBBCBB1),
            onSecondary = Color(0xFF364431),
            secondaryContainer = Color(0xFF313F2C),
            onSecondaryContainer = Color(0xFFB4C4AA),
            tertiary = Color(0xFFFFDCBF),
            onTertiary = Color(0xFF6D4A28),
            tertiaryContainer = Color(0xFFFDCB9E),
            onTertiaryContainer = Color(0xFF644220),
            background = Color(0xFF0E0E0E),
            onBackground = Color(0xFFE5E5E5),
            surface = Color(0xFF0E0E0E),
            onSurface = Color(0xFFE5E5E5),
            surfaceVariant = Color(0xFF262626),
            onSurfaceVariant = Color(0xFF939393),
            surfaceTint = Color(0xFF78FC61),
            inverseSurface = Color(0xFFF9F9F9),
            inverseOnSurface = Color(0xFF555555),
            error = Color(0xFFFF7164),
            onError = Color(0xFF4A0002),
            errorContainer = Color(0xFFAC0C12),
            onErrorContainer = Color(0xFFFFB8B0),
            outline = Color(0xFF757575),
            outlineVariant = Color(0xFF484848),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFF2C2C2C),
            surfaceContainer = Color(0xFF191919),
            surfaceContainerHigh = Color(0xFF1F1F1F),
            surfaceContainerHighest = Color(0xFF262626),
            surfaceContainerLow = Color(0xFF131313),
            surfaceContainerLowest = Color(0xFF000000),
            surfaceDim = Color(0xFF0E0E0E),
            primaryFixed = Color(0xFF78FC61),
            primaryFixedDim = Color(0xFF6AED54),
            onPrimaryFixed = Color(0xFF024900),
            onPrimaryFixedVariant = Color(0xFF036900),
            secondaryFixed = Color(0xFFD7E8CD),
            secondaryFixedDim = Color(0xFFC9D9BF),
            onSecondaryFixed = Color(0xFF354330),
            onSecondaryFixedVariant = Color(0xFF51604B),
            tertiaryFixed = Color(0xFFFDCB9E),
            tertiaryFixedDim = Color(0xFFEEBD91),
            onTertiaryFixed = Color(0xFF4E2F0F),
            onTertiaryFixedVariant = Color(0xFF6E4B28),
        )
}
