package org.nekomanga.presentation.theme.colorschemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object NekoColorScheme : BaseColorScheme() {

    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFFC80036),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFFFDAD9),
            onPrimaryContainer = Color(0xFF41000B),
            inversePrimary = Color(0xFFFFB2B6),
            secondary = Color(0xFF7D5759),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFFFDAD9),
            onSecondaryContainer = Color(0xFF301518),
            tertiary = Color(0xFF7A5260),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFFFD9E2),
            onTertiaryContainer = Color(0xFF2D111E),
            background = Color(0xFFFFF8F7),
            onBackground = Color(0xFF2A2220),
            surface = Color(0xFFFFF8F7),
            onSurface = Color(0xFF2A2220),
            surfaceVariant = Color(0xFFF4DDDD),
            onSurfaceVariant = Color(0xFF524343),
            surfaceTint = Color(0xFFC80036),
            inverseSurface = Color(0xFF3F2D2D),
            inverseOnSurface = Color(0xFFFBECEB),
            outline = Color(0xFF857373),
            outlineVariant = Color(0xFFD7C1C1),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFFFFF8F7),
            surfaceDim = Color(0xFFE8D0D0),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFFCF0F0),
            surfaceContainer = Color(0xFFF9E7E7),
            surfaceContainerHigh = Color(0xFFF3E2E2),
            surfaceContainerHighest = Color(0xFFECE2E2),
            primaryFixed = Color(0xFFFFDAD9),
            primaryFixedDim = Color(0xFFFFB2B6),
            onPrimaryFixed = Color(0xFF41000B),
            onPrimaryFixedVariant = Color(0xFF9F0024),
            secondaryFixed = Color(0xFFFFDAD9),
            secondaryFixedDim = Color(0xFFE8BCBC),
            onSecondaryFixed = Color(0xFF301518),
            onSecondaryFixedVariant = Color(0xFF634143),
            tertiaryFixed = Color(0xFFFFD9E2),
            tertiaryFixedDim = Color(0xFFE8BCBC),
            onTertiaryFixed = Color(0xFF2D111E),
            onTertiaryFixedVariant = Color(0xFF613C47),
        )

    // Generated using MaterialKolor Builder version 1.2.1 (103)
    // https://materialkolor.com/?color_seed=FF6EFFAE&color_primary=FF6EFFAE&color_tertiary=FF3DDA83&color_neutral=FF292929&color_neutralvariant=FF292929&dark_mode=true&style=Rainbow&color_spec=SPEC_2025&package_name=com.example.app
    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFF6CFDAC),
            onPrimary = Color(0xFF005E37),
            primaryContainer = Color(0xFF07BB71),
            onPrimaryContainer = Color(0xFF002C17),
            inversePrimary = Color(0xFF006D40),
            secondary = Color(0xFFB5CCBA),
            onSecondary = Color(0xFF314537),
            secondaryContainer = Color(0xFF2C4032),
            onSecondaryContainer = Color(0xFFAEC5B3),
            tertiary = Color(0xFFC2FFD0),
            onTertiary = Color(0xFF006838),
            tertiaryContainer = Color(0xFF67FEA2),
            onTertiaryContainer = Color(0xFF005F32),
            background = Color(0xFF0E0E0E),
            onBackground = Color(0xFFE7E5E4),
            surface = Color(0xFF0E0E0E),
            onSurface = Color(0xFFE7E5E4),
            surfaceVariant = Color(0xFF262626),
            onSurfaceVariant = Color(0xFF949393),
            surfaceTint = Color(0xFF6CFDAC),
            inverseSurface = Color(0xFFFCF9F8),
            inverseOnSurface = Color(0xFF555555),
            error = Color(0xFFFF7164),
            onError = Color(0xFF4A0002),
            errorContainer = Color(0xFFAC0C12),
            onErrorContainer = Color(0xFFFFB8B0),
            outline = Color(0xFF767575),
            outlineVariant = Color(0xFF484848),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFF2C2C2C),
            surfaceContainer = Color(0xFF191A1A),
            surfaceContainerHigh = Color(0xFF1F2020),
            surfaceContainerHighest = Color(0xFF262626),
            surfaceContainerLow = Color(0xFF131313),
            surfaceContainerLowest = Color(0xFF000000),
            surfaceDim = Color(0xFF0E0E0E),
            primaryFixed = Color(0xFF6CFDAC),
            primaryFixedDim = Color(0xFF5CEE9F),
            onPrimaryFixed = Color(0xFF004A29),
            onPrimaryFixedVariant = Color(0xFF00693E),
            secondaryFixed = Color(0xFFD1E8D5),
            secondaryFixedDim = Color(0xFFC3DAC7),
            onSecondaryFixed = Color(0xFF304436),
            onSecondaryFixedVariant = Color(0xFF4C6051),
            tertiaryFixed = Color(0xFF67FEA2),
            tertiaryFixedDim = Color(0xFF57EF96),
            onTertiaryFixed = Color(0xFF004A26),
            onTertiaryFixedVariant = Color(0xFF006A39),
        )
}
