package org.nekomanga.presentation.theme.colorschemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object NekoColorScheme : BaseColorScheme() {

    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFFC80036),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFFFDAD9),
            onPrimaryContainer = Color(0xFF41000B),
            inversePrimary = Color(0xFFFFB2B6),
            secondary = Color(0xFF7D5759),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFFFDAD9),
            onSecondaryContainer = Color(0xFF301518),
            tertiary = Color(0xFF7A5260),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFFFD9E2),
            onTertiaryContainer = Color(0xFF2D111E),
            background = Color(0xFFFFF8F7),
            onBackground = Color(0xFF2A2220),
            surface = Color(0xFFFFF8F7),
            onSurface = Color(0xFF2A2220),
            surfaceVariant = Color(0xFFF4DDDD),
            onSurfaceVariant = Color(0xFF524343),
            surfaceTint = Color(0xFFC80036),
            inverseSurface = Color(0xFF3F2D2D),
            inverseOnSurface = Color(0xFFFBECEB),
            outline = Color(0xFF857373),
            outlineVariant = Color(0xFFD7C1C1),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFFFFF8F7),
            surfaceDim = Color(0xFFE8D0D0),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFFCF0F0),
            surfaceContainer = Color(0xFFF9E7E7),
            surfaceContainerHigh = Color(0xFFF3E2E2),
            surfaceContainerHighest = Color(0xFFECE2E2),
            primaryFixed = Color(0xFFFFDAD9),
            primaryFixedDim = Color(0xFFFFB2B6),
            onPrimaryFixed = Color(0xFF41000B),
            onPrimaryFixedVariant = Color(0xFF9F0024),
            secondaryFixed = Color(0xFFFFDAD9),
            secondaryFixedDim = Color(0xFFE8BCBC),
            onSecondaryFixed = Color(0xFF301518),
            onSecondaryFixedVariant = Color(0xFF634143),
            tertiaryFixed = Color(0xFFFFD9E2),
            tertiaryFixedDim = Color(0xFFE8BCBC),
            onTertiaryFixed = Color(0xFF2D111E),
            onTertiaryFixedVariant = Color(0xFF613C47),
        )

    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFFFFB2B6), // Lightened for better contrast against dark background
            onPrimary = Color(0xFF76001A), // Darkened for better contrast on the new light primary
            primaryContainer = Color(0xFFA00028),
            onPrimaryContainer = Color(0xFFFFDAD9),
            inversePrimary = Color(0xFFC80036),
            secondary = Color(0xFFE8BCBC),
            onSecondary = Color(0xFF48292C),
            secondaryContainer = Color(0xFF634143),
            onSecondaryContainer = Color(0xFFFFDAD9),
            tertiary = Color(0xFFE8BCBC),
            onTertiary = Color(0xFF472633),
            tertiaryContainer = Color(0xFF613C47),
            onTertiaryContainer = Color(0xFFFFD9E2),
            background = Color(0xFF2A2220),
            onBackground = Color(0xFFFBECEB),
            surface = Color(0xFF2A2220),
            onSurface = Color(0xFFFBECEB),
            surfaceVariant = Color(0xFF5C4F4B),
            onSurfaceVariant = Color(0xFFD7C1C1),
            surfaceTint = Color(0xFFFFB2B6),
            inverseSurface = Color(0xFFFBECEB),
            inverseOnSurface = Color(0xFF2A2220),
            outline = Color(0xFF9F8D8D),
            outlineVariant = Color(0xFF5C4F4B),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFF5C4F4B),
            surfaceDim = Color(0xFF2A2220),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            surfaceContainerLowest = Color(0xFF1F1816),
            surfaceContainerLow = Color(0xFF302725),
            surfaceContainer = Color(0xFF372D2B),
            surfaceContainerHigh = Color(0xFF433936),
            surfaceContainerHighest = Color(0xFF4E433F),
            primaryFixed = Color(0xFFFFDAD9),
            primaryFixedDim = Color(0xFFFFB2B6),
            onPrimaryFixed = Color(0xFF41000B),
            onPrimaryFixedVariant = Color(0xFF9F0024),
            secondaryFixed = Color(0xFFFFDAD9),
            secondaryFixedDim = Color(0xFFE8BCBC),
            onSecondaryFixed = Color(0xFF301518),
            onSecondaryFixedVariant = Color(0xFF634143),
            tertiaryFixed = Color(0xFFFFD9E2),
            tertiaryFixedDim = Color(0xFFE8BCBC),
            onTertiaryFixed = Color(0xFF2D111E),
            onTertiaryFixedVariant = Color(0xFF613C47),
        )
}
