package org.nekomanga.presentation.theme.colorschemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object NeonColorScheme : BaseColorScheme() {
    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFF8A6C00),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFFFE08C),
            onPrimaryContainer = Color(0xFF2C2100),
            inversePrimary = Color(0xFFEAC248),
            secondary = Color(0xFFB00069),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFFFD9E4),
            onSecondaryContainer = Color(0xFF3D0020),
            tertiary = Color(0xFF006A6A),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFF6FF7F6),
            onTertiaryContainer = Color(0xFF002020),
            background = Color(0xFFF2F2F2),
            onBackground = Color(0xFF1B1B1B),
            surface = Color(0xFFF2F2F2),
            onSurface = Color(0xFF1B1B1B),
            surfaceVariant = Color(0xFFE0E0E0),
            onSurfaceVariant = Color(0xFF424242),
            surfaceTint = Color(0xFF8A6C00),
            inverseSurface = Color(0xFF303030),
            inverseOnSurface = Color(0xFFF3F3F3),
            outline = Color(0xFF72796F),
            outlineVariant = Color(0xFFC2C9BE),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFECECEC),
            surfaceContainer = Color(0xFFE8E8E8),
            surfaceContainerHigh = Color(0xFFE2E2E2),
            surfaceContainerHighest = Color(0xFFDCDCDC),
            primaryFixed = Color(0xFFFFE08C),
            primaryFixedDim = Color(0xFFEAC248),
            onPrimaryFixed = Color(0xFF2C2100),
            onPrimaryFixedVariant = Color(0xFF6B5200),
            secondaryFixed = Color(0xFFFFD9E4),
            secondaryFixedDim = Color(0xFFFFB1C9),
            onSecondaryFixed = Color(0xFF3D0020),
            onSecondaryFixedVariant = Color(0xFF8D004F),
            tertiaryFixed = Color(0xFF6FF7F6),
            tertiaryFixedDim = Color(0xFF4CDADA),
            onTertiaryFixed = Color(0xFF002020),
            onTertiaryFixedVariant = Color(0xFF004F4F),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFFF2F2F2),
            surfaceDim = Color(0xFFD5D5D5),
        )

    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFF3DDA83),
            onPrimary = Color(0xFF003916),
            primaryContainer = Color(0xFF005323),
            onPrimaryContainer = Color(0xFF5CFD9C),
            inversePrimary = Color(0xFF006D31),
            secondary = Color(0xFFC4BFFF),
            onSecondary = Color(0xFF2C2459),
            secondaryContainer = Color(0xFF433B71),
            onSecondaryContainer = Color(0xFFE1DFFF),
            tertiary = Color(0xFFA0C9FF),
            onTertiary = Color(0xFF003258),
            tertiaryContainer = Color(0xFF00497C),
            onTertiaryContainer = Color(0xFFD1E4FF),
            background = Color(0xFF1A1C19),
            onBackground = Color(0xFFE2E3DD),
            surface = Color(0xFF1A1C19),
            onSurface = Color(0xFFE2E3DD),
            surfaceVariant = Color(0xFF424940),
            onSurfaceVariant = Color(0xFFC2C9BE),
            surfaceTint = Color(0xFF3DDA83),
            inverseSurface = Color(0xFFE2E3DD),
            inverseOnSurface = Color(0xFF1A1C19),
            outline = Color(0xFF8C9388),
            outlineVariant = Color(0xFF424940),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            surfaceContainerLowest = Color(0xFF121411),
            surfaceContainerLow = Color(0xFF1A1C19),
            surfaceContainer = Color(0xFF1E201D),
            surfaceContainerHigh = Color(0xFF282B27),
            surfaceContainerHighest = Color(0xFF333632),
            primaryFixed = Color(0xFF79FAAD),
            primaryFixedDim = Color(0xFF5CFD9C),
            onPrimaryFixed = Color(0xFF00210A),
            onPrimaryFixedVariant = Color(0xFF005224),
            secondaryFixed = Color(0xFFE1DFFF),
            secondaryFixedDim = Color(0xFFC4BFFF),
            onSecondaryFixed = Color(0xFF170E44),
            onSecondaryFixedVariant = Color(0xFF423B70),
            tertiaryFixed = Color(0xFFD1E4FF),
            tertiaryFixedDim = Color(0xFFA0C9FF),
            onTertiaryFixed = Color(0xFF001D35),
            onTertiaryFixedVariant = Color(0xFF004A7D),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFF3F413D),
            surfaceDim = Color(0xFF1A1C19),
        )
}
