package org.nekomanga.presentation.theme.colorschemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object OrangeColorScheme : BaseColorScheme() {
    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFFFF671C),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFFFC6AE),
            onPrimaryContainer = Color(0xFF4C1500),
            secondary = Color(0xFFA5CC00),
            onSecondary = Color(0xFF000000),
            secondaryContainer = Color(0xFFE7FFAB),
            onSecondaryContainer = Color(0xFF1D2E00),
            tertiary = Color(0xFFD12D08),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFFFDBCE),
            onTertiaryContainer = Color(0xFF430500),
            background = Color(0xFFFFF8F6),
            onBackground = Color(0xFF373130),
            surface = Color(0xFFFFF8F6),
            onSurface = Color(0xFF373130),
            surfaceVariant = Color(0xFFEBE0DE),
            onSurfaceVariant = Color(0xFF655D5C),
            surfaceTint = Color(0xFFD15520),
            inverseSurface = Color(0xFF100E0D),
            inverseOnSurface = Color(0xFFA19C9B),
            error = Color(0xFF9E3F4E),
            onError = Color(0xFFFFF7F7),
            errorContainer = Color(0xFFFF8B9A),
            onErrorContainer = Color(0xFF782232),
            outline = Color(0xFF817977),
            outlineVariant = Color(0xFFB9B0AE),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFFFFF8F6),
            surfaceContainer = Color(0xFFF5ECEA),
            surfaceContainerHigh = Color(0xFFF0E6E4),
            surfaceContainerHighest = Color(0xFFEBE0DE),
            surfaceContainerLow = Color(0xFFFAF2F0),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceDim = Color(0xFFE3D8D5),
            primaryFixed = Color(0xFFFFDBD2),
            primaryFixedDim = Color(0xFFFFC8BA),
            onPrimaryFixed = Color(0xFF7C1A00),
            onPrimaryFixedVariant = Color(0xFFAC2C07),
            secondaryFixed = Color(0xFFFFDDAE),
            secondaryFixedDim = Color(0xFFFFC8BA),
            onSecondaryFixed = Color(0xFF2A1800),
            onSecondaryFixedVariant = Color(0xFF5A3E00),
            tertiaryFixed = Color(0xFFFFDAD3),
            tertiaryFixedDim = Color(0xFFFFB4A2),
            onTertiaryFixed = Color(0xFF3B0000),
            onTertiaryFixedVariant = Color(0xFF800700),
        )

    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFFFFC07F),
            onPrimary = Color(0xFF752400),
            primaryContainer = Color(0xFFA55100),
            onPrimaryContainer = Color(0xFFFFC07F),
            secondary = Color(0xFFCCFF66),
            onSecondary = Color(0xFF1D2E00),
            secondaryContainer = Color(0xFF304000),
            onSecondaryContainer = Color(0xFFE7FFAB),
            tertiary = Color(0xFFFFB69B),
            onTertiary = Color(0xFF631900),
            tertiaryContainer = Color(0xFF8C3411),
            onTertiaryContainer = Color(0xFFFFDBCE),
            background = Color(0xFF100E0D),
            onBackground = Color(0xFFEEE3E1),
            surface = Color(0xFF100E0D),
            onSurface = Color(0xFFEEE3E1),
            surfaceVariant = Color(0xFF4C4442),
            onSurfaceVariant = Color(0xFFD0C4C1),
            surfaceTint = Color(0xFFFFB69B),
            inverseSurface = Color(0xFFFFF8F6),
            inverseOnSurface = Color(0xFF373130),
            error = Color(0xFFEC7C8A),
            onError = Color(0xFF490013),
            errorContainer = Color(0xFF7F2737),
            onErrorContainer = Color(0xFFFF97A3),
            outline = Color(0xFF998E8C),
            outlineVariant = Color(0xFF4D4645),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFF38312F),
            surfaceContainer = Color(0xFF1C1918),
            surfaceContainerHigh = Color(0xFF231F1E),
            surfaceContainerHighest = Color(0xFF2A2523),
            surfaceContainerLow = Color(0xFF161312),
            surfaceContainerLowest = Color(0xFF000000),
            surfaceDim = Color(0xFF100E0D),
            primaryFixed = Color(0xFFFFDBD2),
            primaryFixedDim = Color(0xFFFFC8BA),
            onPrimaryFixed = Color(0xFF7C1A00),
            onPrimaryFixedVariant = Color(0xFFAC2C07),
            secondaryFixed = Color(0xFFFFDDAE),
            secondaryFixedDim = Color(0xFFFFC8BA),
            onSecondaryFixed = Color(0xFF2A1800),
            onSecondaryFixedVariant = Color(0xFF5A3E00),
            tertiaryFixed = Color(0xFFFFDAD3),
            tertiaryFixedDim = Color(0xFFFFB4A2),
            onTertiaryFixed = Color(0xFF3B0000),
            onTertiaryFixedVariant = Color(0xFF800700),
        )
}
