package org.nekomanga.presentation.theme.colorschemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object OrangeColorScheme : BaseColorScheme() {
    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFFFF6740),
            onPrimary = Color(0xFF000000),
            primaryContainer = Color(0xFFFF8463),
            onPrimaryContainer = Color(0xFF000000),
            secondary = Color(0xFFFF6740),
            onSecondary = Color(0xFF000000),
            secondaryContainer = Color(0xFFFF8463),
            onSecondaryContainer = Color(0xFF000000),
            tertiary = Color(0xFFFF6840),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFFF8463),
            onTertiaryContainer = Color(0xFFFFFFFF),
            background = Color(0xFFFFF8F6),
            onBackground = Color(0xFF373130),
            surface = Color(0xFFFFF8F6),
            onSurface = Color(0xFF373130),
            surfaceVariant = Color(0xFFEBE0DE),
            onSurfaceVariant = Color(0xFF655D5C),
            surfaceTint = Color(0xFFB02F0B),
            inverseSurface = Color(0xFF100E0D),
            inverseOnSurface = Color(0xFFA19C9B),
            error = Color(0xFF9E3F4E),
            onError = Color(0xFFFFF7F7),
            errorContainer = Color(0xFFFF8B9A),
            onErrorContainer = Color(0xFF782232),
            outline = Color(0xFF817977),
            outlineVariant = Color(0xFFB9B0AE),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFFFFF8F6),
            surfaceContainer = Color(0xFFF5ECEA),
            surfaceContainerHigh = Color(0xFFF0E6E4),
            surfaceContainerHighest = Color(0xFFEBE0DE),
            surfaceContainerLow = Color(0xFFFAF2F0),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceDim = Color(0xFFE3D8D5),
            primaryFixed = Color(0xFFFFDBD2),
            primaryFixedDim = Color(0xFFFFC8BA),
            onPrimaryFixed = Color(0xFF7C1A00),
            onPrimaryFixedVariant = Color(0xFFAC2C07),
            secondaryFixed = Color(0xFFFFDBD2),
            secondaryFixedDim = Color(0xFFFFC8BA),
            onSecondaryFixed = Color(0xFF7C1A00),
            onSecondaryFixedVariant = Color(0xFFAC2C07),
            tertiaryFixed = Color(0xFFFF6840),
            tertiaryFixedDim = Color(0xFFEE5C35),
            onTertiaryFixed = Color(0xFF000000),
            onTertiaryFixedVariant = Color(0xFF4C0D00),
        )

    override val darkScheme =
        darkColorScheme(
            primary = lightScheme.primary,
            onPrimary = lightScheme.onPrimary,
            primaryContainer = lightScheme.primaryContainer,
            onPrimaryContainer = lightScheme.onPrimaryContainer,
            secondary = lightScheme.secondary,
            onSecondary = lightScheme.onSecondary,
            secondaryContainer = lightScheme.secondaryContainer,
            onSecondaryContainer = lightScheme.onSecondaryContainer,
            tertiary = lightScheme.tertiary,
            onTertiary = lightScheme.onTertiary,
            tertiaryContainer = lightScheme.tertiaryContainer,
            onTertiaryContainer = lightScheme.onTertiaryContainer,
            background = Color(0xFF100E0D),
            onBackground = Color(0xFFEEE3E1),
            surface = Color(0xFF100E0D),
            onSurface = Color(0xFFEEE3E1),
            surfaceVariant = Color(0xFF2A2523),
            onSurfaceVariant = Color(0xFF9A918F),
            surfaceTint = Color(0xFFFFB4A2),
            inverseSurface = Color(0xFFFFF8F6),
            inverseOnSurface = Color(0xFF585453),
            error = Color(0xFFEC7C8A),
            onError = Color(0xFF490013),
            errorContainer = Color(0xFF7F2737),
            onErrorContainer = Color(0xFFFF97A3),
            outline = Color(0xFF7C7472),
            outlineVariant = Color(0xFF4D4645),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFF312B29),
            surfaceContainer = Color(0xFF1C1918),
            surfaceContainerHigh = Color(0xFF231F1E),
            surfaceContainerHighest = Color(0xFF2A2523),
            surfaceContainerLow = Color(0xFF161312),
            surfaceContainerLowest = Color(0xFF000000),
            surfaceDim = Color(0xFF100E0D),
            primaryFixed = Color(0xFFFFDBD2),
            primaryFixedDim = Color(0xFFFFC8BA),
            onPrimaryFixed = Color(0xFF7C1A00),
            onPrimaryFixedVariant = Color(0xFFAC2C07),
            secondaryFixed = Color(0xFFFFDBD2),
            secondaryFixedDim = Color(0xFFFFC8BA),
            onSecondaryFixed = Color(0xFF7C1A00),
            onSecondaryFixedVariant = Color(0xFFAC2C07),
            tertiaryFixed = Color(0xFFFF6840),
            tertiaryFixedDim = Color(0xFFEE5C35),
            onTertiaryFixed = Color(0xFF000000),
            onTertiaryFixedVariant = Color(0xFF4C0D00),
        )
}
