package org.nekomanga.presentation.theme.colorschemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object PinkColorScheme : BaseColorScheme() {
    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFFB52367),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFFFD9E1),
            onPrimaryContainer = Color(0xFF3D001D),
            inversePrimary = Color(0xFFFFB0CB),
            secondary = Color(0xFF755961),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFFFD9E1),
            onSecondaryContainer = Color(0xFF2B171F),
            tertiary = Color(0xFF825442),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFFFDBCA),
            onTertiaryContainer = Color(0xFF311306),
            background = Color(0xFFFFFBFB),
            onBackground = Color(0xFF1D1B1C),
            surface = Color(0xFFFFFBFB),
            onSurface = Color(0xFF1D1B1C),
            surfaceVariant = Color(0xFFF1DDE1),
            onSurfaceVariant = Color(0xFF524347),
            surfaceTint = Color(0xFFB52367),
            inverseSurface = Color(0xFF323030),
            inverseOnSurface = Color(0xFFF5F0F0),
            outline = Color(0xFF847377),
            outlineVariant = Color(0xFFD5C2C6),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFFFFFBFB),
            surfaceDim = Color(0xFFDCDFE4),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFFDF0F3),
            surfaceContainer = Color(0xFFF7EBEB),
            surfaceContainerHigh = Color(0xFFF2E5E6),
            surfaceContainerHighest = Color(0xFFECE0E0),
            primaryFixed = Color(0xFFFFD9E1),
            primaryFixedDim = Color(0xFFFFB0CB),
            onPrimaryFixed = Color(0xFF3D001D),
            onPrimaryFixedVariant = Color(0xFF8F004D),
            secondaryFixed = Color(0xFFFFD9E1),
            secondaryFixedDim = Color(0xFFE4BDC6),
            onSecondaryFixed = Color(0xFF2B171F),
            onSecondaryFixedVariant = Color(0xFF5B3F49),
            tertiaryFixed = Color(0xFFFFDBCA),
            tertiaryFixedDim = Color(0xFFFFB995),
            onTertiaryFixed = Color(0xFF311306),
            onTertiaryFixedVariant = Color(0xFF693B2D),
        )

    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFFFFB0CB),
            onPrimary = Color(0xFF650036),
            primaryContainer = Color(0xFF8F004D),
            onPrimaryContainer = Color(0xFFFFD9E1),
            inversePrimary = Color(0xFFB52367),
            secondary = Color(0xFFE4BDC6),
            onSecondary = Color(0xFF422832),
            secondaryContainer = Color(0xFF5B3F49),
            onSecondaryContainer = Color(0xFFFFD9E1),
            tertiary = Color(0xFFFFB995),
            onTertiary = Color(0xFF4F2519),
            tertiaryContainer = Color(0xFF693B2D),
            onTertiaryContainer = Color(0xFFFFDBCA),
            background = Color(0xFF1D1B1C),
            onBackground = Color(0xFFE7E0E1),
            surface = Color(0xFF1D1B1C),
            onSurface = Color(0xFFE7E0E1),
            surfaceVariant = Color(0xFF524347),
            onSurfaceVariant = Color(0xFFD5C2C6),
            surfaceTint = Color(0xFFFFB0CB),
            inverseSurface = Color(0xFFE7E0E1),
            inverseOnSurface = Color(0xFF1D1B1C),
            outline = Color(0xFF9F8D91),
            outlineVariant = Color(0xFF524347),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFF403C3D),
            surfaceDim = Color(0xFF1D1B1C),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            surfaceContainerLowest = Color(0xFF121011),
            surfaceContainerLow = Color(0xFF252324),
            surfaceContainer = Color(0xFF292728),
            surfaceContainerHigh = Color(0xFF343233),
            surfaceContainerHighest = Color(0xFF3D3C3D),
            primaryFixed = Color(0xFFFFD9E1),
            primaryFixedDim = Color(0xFFFFB0CB),
            onPrimaryFixed = Color(0xFF3D001D),
            onPrimaryFixedVariant = Color(0xFF8F004D),
            secondaryFixed = Color(0xFFFFD9E1),
            secondaryFixedDim = Color(0xFFE4BDC6),
            onSecondaryFixed = Color(0xFF2B171F),
            onSecondaryFixedVariant = Color(0xFF5B3F49),
            tertiaryFixed = Color(0xFFFFDBCA),
            tertiaryFixedDim = Color(0xFFFFB995),
            onTertiaryFixed = Color(0xFF311306),
            onTertiaryFixedVariant = Color(0xFF693B2D),
        )
}
