package org.nekomanga.presentation.theme.colorschemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object PinkColorScheme : BaseColorScheme() {
    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFFFF85A1),
            onPrimary = Color(0xFF000000),
            primaryContainer = Color(0xFFFFD9E2),
            onPrimaryContainer = Color(0xFF3D001D),
            inversePrimary = Color(0xFFFFB0CB),
            secondary = Color(0xFF634B52),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFEBDFE4),
            onSecondaryContainer = Color(0xFF1E0711),
            tertiary = Color(0xFF7C837C),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFD6E7D5),
            onTertiaryContainer = Color(0xFF0D1E13),
            background = Color(0xFFFFFBFB),
            onBackground = Color(0xFF1D1B1C),
            surface = Color(0xFFFFFBFB),
            onSurface = Color(0xFF1D1B1C),
            surfaceVariant = Color(0xFFF1DDE1),
            onSurfaceVariant = Color(0xFF524347),
            surfaceTint = Color(0xFFFF85A1),
            inverseSurface = Color(0xFF323030),
            inverseOnSurface = Color(0xFFF5F0F0),
            outline = Color(0xFF847377),
            outlineVariant = Color(0xFFD5C2C6),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFFFFFBFB),
            surfaceDim = Color(0xDCDFE4),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFFDF0F3),
            surfaceContainer = Color(0xFFF7EBEB),
            surfaceContainerHigh = Color(0xFFF2E5E6),
            surfaceContainerHighest = Color(0xFFECE0E0),
            primaryFixed = Color(0xFFFFD9E1),
            primaryFixedDim = Color(0xFFFFB0CB),
            onPrimaryFixed = Color(0xFF3D001D),
            onPrimaryFixedVariant = Color(0xFF8F004D),
            secondaryFixed = Color(0xFFEBDFE4),
            secondaryFixedDim = Color(0xFFCEBCC2),
            onSecondaryFixed = Color(0xFF1E0711),
            onSecondaryFixedVariant = Color(0xFF4A343A),
            tertiaryFixed = Color(0xFFD6E7D5),
            tertiaryFixedDim = Color(0xFFB9CCB8),
            onTertiaryFixed = Color(0xFF0D1E13),
            onTertiaryFixedVariant = Color(0xFF3F4A3F),
        )

    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFFFFB0CB),
            onPrimary = Color(0xFF670034),
            primaryContainer = Color(0xFF7D3452),
            onPrimaryContainer = Color(0xFFFFD9E2),
            inversePrimary = Color(0xFFFF338D),
            secondary = Color(0xFFCEBCC2),
            onSecondary = Color(0xFF352B31),
            secondaryContainer = Color(0xFF4A343A),
            onSecondaryContainer = Color(0xFFEBDFE4),
            tertiary = Color(0xFFB9CCB8),
            onTertiary = Color(0xFF2E332E),
            tertiaryContainer = Color(0xFF3F4A3F),
            onTertiaryContainer = Color(0xFFD6E7D5),
            background = Color(0xFF1D1A1B),
            onBackground = Color(0xFFE7E0E1),
            surface = Color(0xFF1D1A1B),
            onSurface = Color(0xFFE7E0E1),
            surfaceVariant = Color(0xFF514347),
            onSurfaceVariant = Color(0xFFD5C2C7),
            surfaceTint = Color(0xFFFFB0CB),
            inverseSurface = Color(0xFFE7E0E1),
            inverseOnSurface = Color(0xFF1D1A1B),
            outline = Color(0xFF9F8D91),
            outlineVariant = Color(0xFF514347),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFF403C3D),
            surfaceDim = Color(0xFF1D1A1B),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            surfaceContainerLowest = Color(0xFF121011),
            surfaceContainerLow = Color(0xFF252324),
            surfaceContainer = Color(0xFF292728),
            surfaceContainerHigh = Color(0xFF343233),
            surfaceContainerHighest = Color(0xFF3D3C3D),
            primaryFixed = Color(0xFFFFD9E2),
            primaryFixedDim = Color(0xFFFF46A2),
            onPrimaryFixed = Color(0xFF410020),
            onPrimaryFixedVariant = Color(0xFF9E0054),
            secondaryFixed = Color(0xFFEBDFE4),
            secondaryFixedDim = Color(0xFFCEBCC2),
            onSecondaryFixed = Color(0xFF1E0711),
            onSecondaryFixedVariant = Color(0xFF4A343A),
            tertiaryFixed = Color(0xFFD6E7D5),
            tertiaryFixedDim = Color(0xFFB9CCB8),
            onTertiaryFixed = Color(0xFF0D1E13),
            onTertiaryFixedVariant = Color(0xFF3F4A3F),
        )
}
