package org.nekomanga.presentation.theme.colorschemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object PurpleColorScheme : BaseColorScheme() {
    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFF6A3C9F),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFE8DDFF),
            onPrimaryContainer = Color(0xFF2A0054),
            inversePrimary = Color(0xFFCEBCFF),
            secondary = Color(0xFF987200),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFFFE398),
            onSecondaryContainer = Color(0xFF231A00),
            tertiary = Color(0xFF934444),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFFFDAD6),
            onTertiaryContainer = Color(0xFF400010),
            background = Color(0xFFFEF7FF),
            onBackground = Color(0xFF1B1B1F),
            surface = Color(0xFFFEF7FF),
            onSurface = Color(0xFF1B1B1F),
            surfaceVariant = Color(0xFFE8E0F1),
            onSurfaceVariant = Color(0xFF48405B),
            surfaceTint = Color(0xFF6A3C9F),
            inverseSurface = Color(0xFF312843),
            inverseOnSurface = Color(0xFFF1DFFF),
            error = Color(0xFFB3261E),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            outline = Color(0xFF797486),
            outlineVariant = Color(0xFFC9C4D4),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFFFEF7FF),
            surfaceContainer = Color(0xFFF2EBFD),
            surfaceContainerHigh = Color(0xFFEDE5F8),
            surfaceContainerHighest = Color(0xFFE8E0F1),
            surfaceContainerLow = Color(0xFFF7F1FF),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceDim = Color(0xFFDCD6E8),
            primaryFixed = Color(0xFFE8DDFF),
            primaryFixedDim = Color(0xFFCEBCFF),
            onPrimaryFixed = Color(0xFF2E0054),
            onPrimaryFixedVariant = Color(0xFF5A2288),
            secondaryFixed = Color(0xFFF0DBFF),
            secondaryFixedDim = Color(0xFFE6C9FF),
            onSecondaryFixed = Color(0xFF58218B),
            onSecondaryFixedVariant = Color(0xFF7641AA),
            tertiaryFixed = Color(0xFFD4A5FF),
            tertiaryFixedDim = Color(0xFFCA93FF),
            onTertiaryFixed = Color(0xFF33005C),
            onTertiaryFixedVariant = Color(0xFF59208C),
        )
    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFFCEBFFF),
            onPrimary = Color(0xFF450099),
            primaryContainer = Color(0xFF5F29B4),
            onPrimaryContainer = Color(0xFFE8DDFF),
            inversePrimary = Color(0xFF6A3C9F),
            secondary = Color(0xFFFFC015),
            onSecondary = Color(0xFF4F3500),
            secondaryContainer = Color(0xFF6B4C00),
            onSecondaryContainer = Color(0xFFFFE398),
            tertiary = Color(0xFFFFB4A4),
            onTertiary = Color(0xFF69000D),
            tertiaryContainer = Color(0xFF8D2C24),
            onTertiaryContainer = Color(0xFFFFDAD6),
            background = Color(0xFF2A1D42),
            onBackground = Color(0xFFE8DDFF),
            surface = Color(0xFF2A1D42),
            onSurface = Color(0xFFE8DDFF),
            surfaceVariant = Color(0xFF4E4461),
            onSurfaceVariant = Color(0xFFCFC3E7),
            surfaceTint = Color(0xFFCEBFFF),
            inverseSurface = Color(0xFFE8DDFF),
            inverseOnSurface = Color(0xFF2A1D42),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            outline = Color(0xFF9A90AF),
            outlineVariant = Color(0xFF4E4461),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFF4A3D5D),
            surfaceContainer = Color(0xFF32254B),
            surfaceContainerHigh = Color(0xFF3F325C),
            surfaceContainerHighest = Color(0xFF4E4461),
            surfaceContainerLow = Color(0xFF2F2148),
            surfaceContainerLowest = Color(0xFF1F1237),
            surfaceDim = Color(0xFF2A1D42),
            primaryFixed = Color(0xFFD9B0FF),
            primaryFixedDim = Color(0xFFCEBFFF),
            onPrimaryFixed = Color(0xFF3D006C),
            onPrimaryFixedVariant = Color(0xFF5F2695),
            secondaryFixed = Color(0xFFFFE398),
            secondaryFixedDim = Color(0xFFFFC015),
            onSecondaryFixed = Color(0xFF58218B),
            onSecondaryFixedVariant = Color(0xFF7641AA),
            tertiaryFixed = Color(0xFFFFDAD6),
            tertiaryFixedDim = Color(0xFFFFB4A4),
            onTertiaryFixed = Color(0xFF33005C),
            onTertiaryFixedVariant = Color(0xFF59208C),
        )
}
