package org.nekomanga.presentation.theme.colorschemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object PurpleColorScheme : BaseColorScheme() {
    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFF9C64D3),
            onPrimary = Color(0xFFEDE2FF),
            primaryContainer = Color(0xFFDED3F3),
            onPrimaryContainer = Color(0xFF9C64D3),
            secondary = Color(0xFF7B46AF),
            onSecondary = Color(0xFFEDE2FF),
            secondaryContainer = Color(0xFFFFFFFF),
            onSecondaryContainer = Color(0xFF9C64D3),
            tertiary = Color(0xFF9C65D1),
            onTertiary = Color(0xFFEDE2FF),
            tertiaryContainer = Color(0xFFBA8EE5),
            onTertiaryContainer = Color(0xFFEDE2FF),
            error = Color(0xFFC14033),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFDC6559),
            onErrorContainer = Color(0xFFFFFFFF),
            background = Color(0xFFEDE2FF),
            onBackground = Color(0xFF000000),
            surface = Color(0xFFEDE2FF),
            onSurface = Color(0xFF000000),
            surfaceVariant = Color(0xFFDED3F3),
            onSurfaceVariant = Color(0xFF000000),
            outline = Color(0xFFD7C1ED),
            outlineVariant = Color(0xFFEBE0F6),
            scrim = Color(0xFFFFFFFF),
            inverseSurface = Color(0xFFFFFFFF),
            inverseOnSurface = Color(0xFFFFFFFF),
            inversePrimary = Color(0xFFD6BAFF),
            surfaceDim = Color(0xFFFFFFFF),
            surfaceBright = Color(0xFFFFFFFF),
            surfaceContainerLowest = Color(0xFFF1E8FF),
            surfaceContainerLow = Color(0xFFEFE5FF),
            surfaceContainer = Color(0xFFEDE2FF),
            surfaceContainerHigh = Color(0xFFD5CBE6),
            surfaceContainerHighest = Color(0xFFBEB5CC),
        )

    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFFA177FF),
            onPrimary = Color(0xFF111129),
            primaryContainer = Color(0xFFBDA0FF),
            onPrimaryContainer = Color(0xFF111129),
            secondary = Color(0xFFA177FF),
            onSecondary = Color(0xFF111129),
            secondaryContainer = Color(0xFFBDA0FF),
            onSecondaryContainer = Color(0xFF111129),
            tertiary = Color(0xFF5E25E1),
            onTertiary = Color(0xFF111129),
            tertiaryContainer = Color(0xFF7A4BE5),
            onTertiaryContainer = Color(0xFF111129),
            error = Color(0xFFC14033),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFDC6559),
            onErrorContainer = Color(0xFFFFFFFF),
            background = Color(0xFF111129),
            onBackground = Color(0xFFDEE8FF),
            surface = Color(0xFF111129),
            onSurface = Color(0xFFDEE8FF),
            surfaceVariant = Color(0xFF201042),
            onSurfaceVariant = Color(0xFFDEE8FF),
            outline = Color(0xFFD9C9FF),
            outlineVariant = Color(0xFFECE4FF),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF000000),
            inverseOnSurface = Color(0xFF000000),
            inversePrimary = Color(0xFFD6BAFF),
            surfaceDim = Color(0xFF000000),
            surfaceBright = Color(0xFF000000),
            surfaceContainerLowest = Color(0xFF0E0E21),
            surfaceContainerLow = Color(0xFF0F0F25),
            surfaceContainer = Color(0xFF111129),
            surfaceContainerHigh = Color(0xFF29293E),
            surfaceContainerHighest = Color(0xFF414154),
        )
}
