package org.nekomanga.presentation.theme.colorschemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object PurpleColorScheme : BaseColorScheme() {
    // Generated using MaterialKolor Builder version 1.2.1 (103)
    // https://materialkolor.com/?color_seed=FF68A500&dark_mode=false&style=Fidelity&selected_preset_id=res-0&color_spec=SPEC_2025&package_name=com.example.app&expressive=true
    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFF7B43B1),
            onPrimary = Color(0xFFFFF6FF),
            primaryContainer = Color(0xFFD9B0FF),
            onPrimaryContainer = Color(0xFF561A8B),
            inversePrimary = Color(0xFFC68CFF),
            secondary = Color(0xFF7A45AE),
            onSecondary = Color(0xFFFFF6FF),
            secondaryContainer = Color(0xFFF0DBFF),
            onSecondaryContainer = Color(0xFF6C369F),
            tertiary = Color(0xFF7B44AE),
            onTertiary = Color(0xFFFFF6FF),
            tertiaryContainer = Color(0xFFD4A5FF),
            onTertiaryContainer = Color(0xFF4F1383),
            background = Color(0xFFFEF7FF),
            onBackground = Color(0xFF372C53),
            surface = Color(0xFFFEF7FF),
            onSurface = Color(0xFF372C53),
            surfaceVariant = Color(0xFFE9DDFF),
            onSurfaceVariant = Color(0xFF655883),
            surfaceTint = Color(0xFF7B43B1),
            inverseSurface = Color(0xFF100B1F),
            inverseOnSurface = Color(0xFFA299B3),
            error = Color(0xFFAC3149),
            onError = Color(0xFFFFF7F7),
            errorContainer = Color(0xFFF76A80),
            onErrorContainer = Color(0xFF68001F),
            outline = Color(0xFF8174A0),
            outlineVariant = Color(0xFFB9ABDA),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFFFEF7FF),
            surfaceContainer = Color(0xFFF3EAFF),
            surfaceContainerHigh = Color(0xFFEEE4FF),
            surfaceContainerHighest = Color(0xFFE9DDFF),
            surfaceContainerLow = Color(0xFFF8F1FF),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceDim = Color(0xFFE2D3FF),
            primaryFixed = Color(0xFFD9B0FF),
            primaryFixedDim = Color(0xFFD09EFF),
            onPrimaryFixed = Color(0xFF3D006C),
            onPrimaryFixedVariant = Color(0xFF5F2695),
            secondaryFixed = Color(0xFFF0DBFF),
            secondaryFixedDim = Color(0xFFE6C9FF),
            onSecondaryFixed = Color(0xFF58218B),
            onSecondaryFixedVariant = Color(0xFF7641AA),
            tertiaryFixed = Color(0xFFD4A5FF),
            tertiaryFixedDim = Color(0xFFCA93FF),
            onTertiaryFixed = Color(0xFF33005C),
            onTertiaryFixedVariant = Color(0xFF59208C),
        )
    // Generated using MaterialKolor Builder version 1.2.1 (103)
    // https://materialkolor.com/?color_seed=FF7A4BE5&color_tertiary=FFE38CFF&dark_mode=true&style=Vibrant&color_spec=SPEC_2025&package_name=com.example.app&expressive=true
    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFFB99EFF),
            onPrimary = Color(0xFF39008D),
            primaryContainer = Color(0xFFAD8DFF),
            onPrimaryContainer = Color(0xFF2B006F),
            inversePrimary = Color(0xFF6D3CD7),
            secondary = Color(0xFFC591FD),
            onSecondary = Color(0xFF3F0073),
            secondaryContainer = Color(0xFF5E2C92),
            onSecondaryContainer = Color(0xFFE2C5FF),
            tertiary = Color(0xFFE9A0FF),
            onTertiary = Color(0xFF60037E),
            tertiaryContainer = Color(0xFFE38CFF),
            onTertiaryContainer = Color(0xFF50006B),
            background = Color(0xFF16052A),
            onBackground = Color(0xFFF1DFFF),
            surface = Color(0xFF16052A),
            onSurface = Color(0xFFF1DFFF),
            surfaceVariant = Color(0xFF32194E),
            onSurfaceVariant = Color(0xFFA18AB7),
            surfaceTint = Color(0xFFB99EFF),
            inverseSurface = Color(0xFFFFF7FF),
            inverseOnSurface = Color(0xFF614D75),
            error = Color(0xFFFF6E84),
            onError = Color(0xFF490013),
            errorContainer = Color(0xFFA70138),
            onErrorContainer = Color(0xFFFFB2B9),
            outline = Color(0xFF826D97),
            outlineVariant = Color(0xFF563C73),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFF3A1E57),
            surfaceContainer = Color(0xFF240E3B),
            surfaceContainerHigh = Color(0xFF2B1344),
            surfaceContainerHighest = Color(0xFF32194E),
            surfaceContainerLow = Color(0xFF1D0832),
            surfaceContainerLowest = Color(0xFF000000),
            surfaceDim = Color(0xFF16052A),
            primaryFixed = Color(0xFFAD8DFF),
            primaryFixedDim = Color(0xFFA17CFF),
            onPrimaryFixed = Color(0xFF000000),
            onPrimaryFixedVariant = Color(0xFF360087),
            secondaryFixed = Color(0xFFE3C6FF),
            secondaryFixedDim = Color(0xFFDAB5FF),
            onSecondaryFixed = Color(0xFF4A147E),
            onSecondaryFixedVariant = Color(0xFF68379C),
            tertiaryFixed = Color(0xFFE490FF),
            tertiaryFixedDim = Color(0xFFD781F3),
            onTertiaryFixed = Color(0xFF2D003E),
            onTertiaryFixedVariant = Color(0xFF60047F),
        )
}
