package org.nekomanga.presentation.theme.colorschemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object RetroColorScheme : BaseColorScheme() {
    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFF60D6FF),
            onPrimary = Color(0xFF00415A),
            primaryContainer = Color(0xFFB2EFFF),
            onPrimaryContainer = Color(0xFF001F2A),
            inversePrimary = Color(0xFF60D6FF),
            secondary = Color(0xFFFF00DD),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFFFD7FA),
            onSecondaryContainer = Color(0xFF520042),
            tertiary = Color(0xFFA744E3),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFF0DAFF),
            onTertiaryContainer = Color(0xFF390066),
            background = Color(0xFFF7F9FF),
            onBackground = Color(0xFF00101C),
            surface = Color(0xFFF7F9FF),
            onSurface = Color(0xFF00101C),
            surfaceVariant = Color(0xFFCBE6FF),
            onSurfaceVariant = Color(0xFF3C6380),
            surfaceTint = Color(0xFF00668A),
            inverseSurface = Color(0xFF00101C),
            inverseOnSurface = Color(0xFF8C9FB2),
            error = Color(0xFFAC3434),
            onError = Color(0xFFFFF7F6),
            errorContainer = Color(0xFFF56965),
            onErrorContainer = Color(0xFF65000B),
            outline = Color(0xFF597F9D),
            outlineVariant = Color(0xFF90B6D7),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFFF7F9FF),
            surfaceContainer = Color(0xFFE1F0FF),
            surfaceContainerHigh = Color(0xFFD6EBFF),
            surfaceContainerHighest = Color(0xFFCBE6FF),
            surfaceContainerLow = Color(0xFFECF4FF),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceDim = Color(0xFFBADEFF),
            primaryFixed = Color(0xFF60D6FF),
            primaryFixedDim = Color(0xFF0CC0FF),
            onPrimaryFixed = Color(0xFF002B3D),
            onPrimaryFixedVariant = Color(0xFF004B66),
            secondaryFixed = Color(0xFFF3C0FF),
            secondaryFixedDim = Color(0xFFEBC6F7),
            onSecondaryFixed = Color(0xFF5A4470),
            onSecondaryFixedVariant = Color(0xFF70526F),
            tertiaryFixed = Color(0xFFFFD6F1),
            tertiaryFixedDim = Color(0xFFEA98DF),
            onTertiaryFixed = Color(0xFF4A0749),
            onTertiaryFixedVariant = Color(0xFF6D2A69),
        )

    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFF60D6FF),
            onPrimary = Color(0xFF00415A),
            primaryContainer = Color(0xFF004D6B),
            onPrimaryContainer = Color(0xFFB2EFFF),
            inversePrimary = Color(0xFF00668A),
            secondary = Color(0xFFFF95F1),
            onSecondary = Color(0xFF5A004F),
            secondaryContainer = Color(0xFF7A0069),
            onSecondaryContainer = Color(0xFFFFD7FA),
            tertiary = Color(0xFFDAA4FF),
            onTertiary = Color(0xFF560086),
            tertiaryContainer = Color(0xFF7100B8),
            onTertiaryContainer = Color(0xFFF0DAFF),
            background = Color(0xFF00101C),
            onBackground = Color(0xFFE0E6EB),
            surface = Color(0xFF00101C),
            onSurface = Color(0xFFE0E6EB),
            surfaceVariant = Color(0xFF3C6380),
            onSurfaceVariant = Color(0xFFC4DCEF),
            surfaceTint = Color(0xFF60D6FF),
            inverseSurface = Color(0xFFE0E6EB),
            inverseOnSurface = Color(0xFF00101C),
            error = Color(0xFFFFB4AC),
            onError = Color(0xFF65000B),
            errorContainer = Color(0xFF8C0015),
            onErrorContainer = Color(0xFFFFDAD6),
            outline = Color(0xFF759FB8),
            outlineVariant = Color(0xFF3C6380),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFF353C43),
            surfaceContainer = Color(0xFF041724),
            surfaceContainerHigh = Color(0xFF091D29),
            surfaceContainerHighest = Color(0xFF102735),
            surfaceContainerLow = Color(0xFF00101C),
            surfaceContainerLowest = Color(0xFF000000),
            surfaceDim = Color(0xFF00101C),
            primaryFixed = Color(0xFF0CC0FF),
            primaryFixedDim = Color(0xFF43C9FF),
            onPrimaryFixed = Color(0xFF002B3D),
            onPrimaryFixedVariant = Color(0xFF004B66),
            secondaryFixed = Color(0xFFFFD7FA),
            secondaryFixedDim = Color(0xFFF3C0FF),
            onSecondaryFixed = Color(0xFF5A004F),
            onSecondaryFixedVariant = Color(0xFF7A0069),
            tertiaryFixed = Color(0xFFFFD6F1),
            tertiaryFixedDim = Color(0xFFF0DAFF),
            onTertiaryFixed = Color(0xFF4A0749),
            onTertiaryFixedVariant = Color(0xFF6D2A69),
        )
}
