package org.nekomanga.presentation.theme.colorschemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object RetroColorScheme : BaseColorScheme() {
    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFF60D6FF), // Electric Blue
            onPrimary = Color(0xFF00415A),
            primaryContainer = Color(0xFF00668A),
            onPrimaryContainer = Color(0xFFF4FAFF),
            inversePrimary = Color(0xFF60D6FF),
            secondary = Color(0xFFFF00DD),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFED80FF),
            onSecondaryContainer = Color(0xFF00415A),
            tertiary = Color(0xFFFFD6F1), // Soft Pink/Magenta Accent
            onTertiary = Color(0xFF733F5A),
            tertiaryContainer = Color(0xFF904F75),
            onTertiaryContainer = Color(0xFFFFF7F9),
            background = Color(0xFFF7F9FF),
            onBackground = Color(0xFF00101C),
            surface = Color(0xFFF7F9FF),
            onSurface = Color(0xFF00101C),
            surfaceVariant = Color(0xFFCBE6FF),
            onSurfaceVariant = Color(0xFF3C6380),
            surfaceTint = Color(0xFF00668A),
            inverseSurface = Color(0xFF00101C),
            inverseOnSurface = Color(0xFF8C9FB2),
            error = Color(0xFFAC3434),
            onError = Color(0xFFFFF7F6),
            errorContainer = Color(0xFFF56965),
            onErrorContainer = Color(0xFF65000B),
            outline = Color(0xFF597F9D),
            outlineVariant = Color(0xFF90B6D7),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFFF7F9FF),
            surfaceContainer = Color(0xFFE1F0FF),
            surfaceContainerHigh = Color(0xFFD6EBFF),
            surfaceContainerHighest = Color(0xFFCBE6FF),
            surfaceContainerLow = Color(0xFFECF4FF),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceDim = Color(0xFFBADEFF),
            primaryFixed = Color(0xFF60D6FF),
            primaryFixedDim = Color(0xFF0CC0FF),
            onPrimaryFixed = Color(0xFF002B3D),
            onPrimaryFixedVariant = Color(0xFF004B66),
            secondaryFixed = Color(0xFFF3C0FF),
            secondaryFixedDim = Color(0xFFEBC6F7),
            onSecondaryFixed = Color(0xFF5A4470),
            onSecondaryFixedVariant = Color(0xFF70526F),
            tertiaryFixed = Color(0xFFFFD6F1),
            tertiaryFixedDim = Color(0xFFEA98DF),
            onTertiaryFixed = Color(0xFF4A0749),
            onTertiaryFixedVariant = Color(0xFF6D2A69),
        )

    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFFFFB5C7),
            onPrimary = Color(0xFF6F2A41),
            primaryContainer = Color(0xFFFEA0BA),
            onPrimaryContainer = Color(0xFF632138),
            inversePrimary = Color(0xFF92475E),
            secondary = Color(0xFFCEBFEF),
            onSecondary = Color(0xFF453A62),
            secondaryContainer = Color(0xFF2A1F45),
            onSecondaryContainer = Color(0xFFAA9DCB),
            tertiary = Color(0xFFE5D2FF),
            onTertiary = Color(0xFF564377),
            tertiaryContainer = Color(0xFFD9C1FE),
            onTertiaryContainer = Color(0xFF4D3A6D),
            background = Color(0xFF120139),
            onBackground = Color(0xFFEBE1FF),
            surface = Color(0xFF120139),
            onSurface = Color(0xFFEBE1FF),
            surfaceVariant = Color(0xFF2C0078),
            onSurfaceVariant = Color(0xFF9D81F0),
            surfaceTint = Color(0xFFFFB5C7),
            inverseSurface = Color(0xFFFDF7FF),
            inverseOnSurface = Color(0xFF5A4C84),
            error = Color(0xFFFD6F85),
            onError = Color(0xFF490013),
            errorContainer = Color(0xFF8A1632),
            onErrorContainer = Color(0xFFFF97A3),
            outline = Color(0xFF7E63CF),
            outlineVariant = Color(0xFF50329D),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFF340089),
            surfaceContainer = Color(0xFF1F0058),
            surfaceContainerHigh = Color(0xFF250068),
            surfaceContainerHighest = Color(0xFF2C0078),
            surfaceContainerLow = Color(0xFF180048),
            surfaceContainerLowest = Color(0xFF000000),
            surfaceDim = Color(0xFF120139),
            primaryFixed = Color(0xFFFFA8BF),
            primaryFixedDim = Color(0xFFF598B2),
            onPrimaryFixed = Color(0xFF4D0F27),
            onPrimaryFixedVariant = Color(0xFF732E44),
            secondaryFixed = Color(0xFFE9DDFF),
            secondaryFixedDim = Color(0xFFDCCDFE),
            onSecondaryFixed = Color(0xFF443961),
            onSecondaryFixedVariant = Color(0xFF61557F),
            tertiaryFixed = Color(0xFFD9C1FE),
            tertiaryFixedDim = Color(0xFFCBB4F0),
            onTertiaryFixed = Color(0xFF392658),
            onTertiaryFixedVariant = Color(0xFF574377),
        )
}
