package org.nekomanga.presentation.theme.colorschemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object TakoColorScheme : BaseColorScheme() {
    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFF66577E),
            onPrimary = Color(0xFFF3B375),
            primaryContainer = Color(0xFF66577E),
            onPrimaryContainer = Color(0xFFF3B375),
            inversePrimary = Color(0xFFD6BAFF),
            secondary = Color(0xFF52526B),
            onSecondary = Color(0xFFFFE3A5),
            secondaryContainer = Color(0xFFD1C7D6),
            onSecondaryContainer = Color(0xFF1E1C24),
            tertiary = Color(0xFFF3B375),
            onTertiary = Color(0xFF574360),
            tertiaryContainer = Color(0xFFFDD6B0),
            onTertiaryContainer = Color(0xFF221437),
            background = Color(0xFFF7F5FF),
            onBackground = Color(0xFF1B1B22),
            surface = Color(0xFFF7F5FF),
            onSurface = Color(0xFF1B1B22),
            surfaceVariant = Color(0xFFE8E0EB),
            onSurfaceVariant = Color(0xFF49454E),
            surfaceTint = Color(0xFF66577E),
            inverseSurface = Color(0xFF313033),
            inverseOnSurface = Color(0xFFF3EFF4),
            outline = Color(0xFF7A757E),
            outlineVariant = Color(0xFFBBA4FF),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFFFDF7FF),
            surfaceDim = Color(0xFFE0D4FF),
            error = Color(0xFFB3261E),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFF9DEDC),
            onErrorContainer = Color(0xFF410E0B),
            surfaceContainerLowest = Color(0xFFD7D0DA),
            surfaceContainerLow = Color(0xFFDFD8E2),
            surfaceContainer = Color(0xFFE8E0EB),
            surfaceContainerHigh = Color(0xFFEEE6F1),
            surfaceContainerHighest = Color(0xFFF7EEFA),
            primaryFixed = Color(0xFF66577E),
            primaryFixedDim = Color(0xFF574B74),
            onPrimaryFixed = Color(0xFFF3B375),
            onPrimaryFixedVariant = Color(0xFFD6BAFF),
            secondaryFixed = Color(0xFFC8BED0),
            secondaryFixedDim = Color(0xFFB4A5C6),
            onSecondaryFixed = Color(0xFF66577E),
            onSecondaryFixedVariant = Color(0xFF49454E),
            tertiaryFixed = Color(0xFFFDD6B0),
            tertiaryFixedDim = Color(0xFFF8C4A6),
            onTertiaryFixed = Color(0xFF221437),
            onTertiaryFixedVariant = Color(0xFF574360),
        )

    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFFF3B375),
            onPrimary = Color(0xFF38294E),
            primaryContainer = Color(0xFF875B2D),
            onPrimaryContainer = Color(0xFFFFDDA5),
            inversePrimary = Color(0xFF84531E),
            secondary = Color(0xFFB6B1D0),
            onSecondary = Color(0xFF2A2737),
            secondaryContainer = Color(0xFF3A3A49),
            onSecondaryContainer = Color(0xFFD1C7D6),
            tertiary = Color(0xFF66577E),
            onTertiary = Color(0xFFF3B375),
            tertiaryContainer = Color(0xFF4E4065),
            onTertiaryContainer = Color(0xFFEDDCFF),
            background = Color(0xFF21212E),
            onBackground = Color(0xFFE3E0F2),
            surface = Color(0xFF21212E),
            onSurface = Color(0xFFE3E0F2),
            surfaceVariant = Color(0xFF2A2A3C),
            onSurfaceVariant = Color(0xFFCBC4CE),
            surfaceTint = Color(0xFFF3B375),
            inverseSurface = Color(0xFFE5E1E6),
            inverseOnSurface = Color(0xFF1B1B1E),
            outline = Color(0xFF958F99),
            outlineVariant = Color(0xFF504A54),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFF3C3C53),
            surfaceDim = Color(0xFF191926),
            error = Color(0xFFF2B8B5),
            onError = Color(0xFF601410),
            errorContainer = Color(0xFF8C1D18),
            onErrorContainer = Color(0xFFF2B8B5),
            surfaceContainerLowest = Color(0xFF20202E),
            surfaceContainerLow = Color(0xFF262636),
            surfaceContainer = Color(0xFF2A2A3C),
            surfaceContainerHigh = Color(0xFF303044),
            surfaceContainerHighest = Color(0xFF36364D),
            primaryFixed = Color(0xFFF3B375),
            primaryFixedDim = Color(0xFFD6A068),
            onPrimaryFixed = Color(0xFF38294E),
            onPrimaryFixedVariant = Color(0xFF4E3D69),
            secondaryFixed = Color(0xFFF3B375),
            secondaryFixedDim = Color(0xFFC8A58F),
            onSecondaryFixed = Color(0xFF38294E),
            onSecondaryFixedVariant = Color(0xFF625451),
            tertiaryFixed = Color(0xFF66577E),
            tertiaryFixedDim = Color(0xFF4F4064),
            onTertiaryFixed = Color(0xFFF3B375),
            onTertiaryFixedVariant = Color(0xFFEDDCFF),
        )
}
