package org.nekomanga.presentation.theme.colorschemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object TakoColorScheme : BaseColorScheme() {
    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFF463561),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFF5E4C7A),
            onPrimaryContainer = Color(0xFFFFFFFF),
            secondary = Color(0xFF66577E),
            onSecondary = Color(0xFFF3B375),
            secondaryContainer = Color(0xFF837796),
            onSecondaryContainer = Color(0xFFFFFFFF),
            tertiary = Color(0xFF101820),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFF1A2127),
            onTertiaryContainer = Color(0xFFFFFFFF),
            error = Color(0xFFC14033),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFDC6559),
            onErrorContainer = Color(0xFFFFFFFF),
            background = Color(0xFFF2EDF7),
            onBackground = Color(0xFF000000),
            surface = Color(0xFFF2EDF7),
            onSurface = Color(0xFF000000),
            surfaceVariant = Color(0xFFE5DCF4),
            onSurfaceVariant = Color(0xFF000000),
            outline = Color(0xFFB5AEC0),
            outlineVariant = Color(0xFFDAD7DF),
            scrim = Color(0xFFFFFFFF),
            inverseSurface = Color(0xFFFFFFFF),
            inverseOnSurface = Color(0xFFFFFFFF),
            inversePrimary = Color(0xFFAC8FD9),
            surfaceDim = Color(0xFFA9A6AD),
            surfaceBright = Color(0xFFF2EDF7),
            surfaceContainerLowest = Color(0xFFF5F1F9),
            surfaceContainerLow = Color(0xFFF3EFF8),
            surfaceContainer = Color(0xFFF2EDF7),
            surfaceContainerHigh = Color(0xFFDAD5DE),
            surfaceContainerHighest = Color(0xFFC2BEC6),
        )

    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFFFCCD9F),
            onPrimary = Color(0xFF3C2004),
            primaryContainer = Color(0xFFFFE2C5),
            onPrimaryContainer = Color(0xFF3C2004),
            secondary = Color(0xFFF3B375),
            onSecondary = Color(0xFF242431),
            secondaryContainer = Color(0xFFF3B375),
            onSecondaryContainer = Color(0xFF242431),
            tertiary = Color(0xFF101820),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFF1A2127),
            onTertiaryContainer = Color(0xFFFFFFFF),
            error = Color(0xFFC14033),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFDC6559),
            onErrorContainer = Color(0xFFFFFFFF),
            background = Color(0xFF21212E),
            onBackground = Color(0xFFFFFFFF),
            surface = Color(0xFF21212E),
            onSurface = Color(0xFFFFFFFF),
            surfaceVariant = Color(0xFF342F40),
            onSurfaceVariant = Color(0xFFFFFFFF),
            outline = Color(0xFFFEEBD9),
            outlineVariant = Color(0xFFFEF5EC),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF000000),
            inverseOnSurface = Color(0xFF000000),
            inversePrimary = Color(0xFFA85D14),
            surfaceDim = Color(0xFF21212E),
            surfaceBright = Color(0xFF21212E),
            surfaceContainerLowest = Color(0xFF1A1A25),
            surfaceContainerLow = Color(0xFF1E1E29),
            surfaceContainer = Color(0xFF21212E),
            surfaceContainerHigh = Color(0xFF373743),
            surfaceContainerHighest = Color(0xFF4D4D58),
        )
}
