package org.nekomanga.presentation.theme.colorschemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object TealColorScheme : BaseColorScheme() {
    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFF006B7B),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFC4EBF3),
            onPrimaryContainer = Color(0xFF001F25),
            inversePrimary = Color(0xFFB1ECFF),
            secondary = Color(0xFFE47055),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFFFDBCC),
            onSecondaryContainer = Color(0xFF351100),
            tertiary = Color(0xFF525D93),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFE0E0FF),
            onTertiaryContainer = Color(0xFF0C194D),
            background = Color(0xFFFBFDFF),
            onBackground = Color(0xFF191C1D),
            surface = Color(0xFFFBFDFF),
            onSurface = Color(0xFF191C1D),
            surfaceVariant = Color(0xFFDAE4E7),
            onSurfaceVariant = Color(0xFF3F484A),
            surfaceTint = Color(0xFF006B7B),
            inverseSurface = Color(0xFF2E3132),
            inverseOnSurface = Color(0xFFEFF1F1),
            outline = Color(0xFF6F797B),
            outlineVariant = Color(0xFFBFC8CC),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFFFFFFFF),
            surfaceDim = Color(0xFFC7D3D5),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF5FAFB),
            surfaceContainer = Color(0xFFEEF5F6),
            surfaceContainerHigh = Color(0xFFE8F0F1),
            surfaceContainerHighest = Color(0xFFE3F1F3),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            primaryFixed = Color(0xFF6DE8F9),
            primaryFixedDim = Color(0xFF006B7B),
            onPrimaryFixed = Color(0xFF001F25),
            onPrimaryFixedVariant = Color(0xFF004D5C),
            secondaryFixed = Color(0xFFCDE7ED),
            secondaryFixedDim = Color(0xFF4A6267),
            onSecondaryFixed = Color(0xFF051F23),
            onSecondaryFixedVariant = Color(0xFF334B50),
            tertiaryFixed = Color(0xFFE0E0FF),
            tertiaryFixedDim = Color(0xFF525D93),
            onTertiaryFixed = Color(0xFF0C194D),
            onTertiaryFixedVariant = Color(0xFF3B447A),
        )

    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFF4EEFCE),
            onPrimary = Color(0xFF003730),
            primaryContainer = Color(0xFF005047),
            onPrimaryContainer = Color(0xFF73F7E5),
            inversePrimary = Color(0xFF006A60),
            secondary = Color(0xFFFFB39D),
            onSecondary = Color(0xFF561F0A),
            secondaryContainer = Color(0xFF74351F),
            onSecondaryContainer = Color(0xFFFFDBCE),
            tertiary = Color(0xFFA1CAE7),
            onTertiary = Color(0xFF14334A),
            tertiaryContainer = Color(0xFF2C4961),
            onTertiaryContainer = Color(0xFFCBE6FF),
            background = Color(0xFF191C1B),
            onBackground = Color(0xFFE0E3E1),
            surface = Color(0xFF191C1B),
            onSurface = Color(0xFFE0E3E1),
            surfaceVariant = Color(0xFF3F4947),
            onSurfaceVariant = Color(0xFFBEC9C7),
            surfaceTint = Color(0xFF4EEFCE),
            inverseSurface = Color(0xFFE0E3E1),
            inverseOnSurface = Color(0xFF191C1B),
            outline = Color(0xFF889391),
            outlineVariant = Color(0xFF3F4947),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFF404846),
            surfaceDim = Color(0xFF191C1B),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            surfaceContainerLowest = Color(0xFF0E1412),
            surfaceContainerLow = Color(0xFF202524),
            surfaceContainer = Color(0xFF242928),
            surfaceContainerHigh = Color(0xFF2F3433),
            surfaceContainerHighest = Color(0xFF3A3F3E),
            primaryFixed = Color(0xFF73F7E5),
            primaryFixedDim = Color(0xFF4EEFCE),
            onPrimaryFixed = Color(0xFF00201C),
            onPrimaryFixedVariant = Color(0xFF005047),
            secondaryFixed = Color(0xFFCCE8E3),
            secondaryFixedDim = Color(0xFFAFCCBA),
            onSecondaryFixed = Color(0xFF06201D),
            onSecondaryFixedVariant = Color(0xFF334B48),
            tertiaryFixed = Color(0xFFCBE6FF),
            tertiaryFixedDim = Color(0xFFA1CAE7),
            onTertiaryFixed = Color(0xFF001E31),
            onTertiaryFixedVariant = Color(0xFF2C4961),
        )
}
