package org.nekomanga.presentation.theme.colorschemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object TealColorScheme : BaseColorScheme() {
    // Generated using MaterialKolor Builder version 1.2.1 (103)
    // https://materialkolor.com/?color_seed=FF5F9C96&dark_mode=false&style=Expressive&color_spec=SPEC_2025&package_name=com.example.app&expressive=true
    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFF296963),
            onPrimary = Color(0xFFE1FFFB),
            primaryContainer = Color(0xFFAAE9E2),
            onPrimaryContainer = Color(0xFF135853),
            inversePrimary = Color(0xFFBDFDF6),
            secondary = Color(0xFF6F5D2F),
            onSecondary = Color(0xFFFFF8EF),
            secondaryContainer = Color(0xFFF9E0A6),
            onSecondaryContainer = Color(0xFF615023),
            tertiary = Color(0xFF7A5A00),
            onTertiary = Color(0xFFFFF8F1),
            tertiaryContainer = Color(0xFFFDC74F),
            onTertiaryContainer = Color(0xFF5B4100),
            background = Color(0xFFE4FFFF),
            onBackground = Color(0xFF00393B),
            surface = Color(0xFFE4FFFF),
            onSurface = Color(0xFF00393B),
            surfaceVariant = Color(0xFFB0EDEF),
            onSurfaceVariant = Color(0xFF2A686A),
            surfaceTint = Color(0xFF296963),
            inverseSurface = Color(0xFF001112),
            inverseOnSurface = Color(0xFF84A3A3),
            error = Color(0xFFAC3434),
            onError = Color(0xFFFFF7F6),
            errorContainer = Color(0xFFF56965),
            onErrorContainer = Color(0xFF65000B),
            outline = Color(0xFF488486),
            outlineVariant = Color(0xFF80BCBE),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFFE4FFFF),
            surfaceContainer = Color(0xFFC8F7F8),
            surfaceContainerHigh = Color(0xFFBCF2F4),
            surfaceContainerHighest = Color(0xFFB0EDEF),
            surfaceContainerLow = Color(0xFFD4FBFC),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceDim = Color(0xFFA1E6E8),
            primaryFixed = Color(0xFFAAE9E2),
            primaryFixedDim = Color(0xFF9CDAD4),
            onPrimaryFixed = Color(0xFF004440),
            onPrimaryFixedVariant = Color(0xFF21615C),
            secondaryFixed = Color(0xFFF9E0A6),
            secondaryFixedDim = Color(0xFFEBD299),
            onSecondaryFixed = Color(0xFF4D3D12),
            onSecondaryFixedVariant = Color(0xFF6B5A2C),
            tertiaryFixed = Color(0xFFFDC74F),
            tertiaryFixedDim = Color(0xFFEDB943),
            onTertiaryFixed = Color(0xFF422F00),
            onTertiaryFixedVariant = Color(0xFF664A00),
        )

    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFF4EEFCE),
            onPrimary = Color(0xFF003730),
            primaryContainer = Color(0xFF005047),
            onPrimaryContainer = Color(0xFF73F7E5),
            inversePrimary = Color(0xFF006A60),
            secondary = Color(0xFFB1CCC6),
            onSecondary = Color(0xFF1C3532),
            secondaryContainer = Color(0xFF334B48),
            onSecondaryContainer = Color(0xFFCCE8E3),
            tertiary = Color(0xFFA1CAE7),
            onTertiary = Color(0xFF14334A),
            tertiaryContainer = Color(0xFF2C4961),
            onTertiaryContainer = Color(0xFFCBE6FF),
            background = Color(0xFF191C1B),
            onBackground = Color(0xFFE0E3E1),
            surface = Color(0xFF191C1B),
            onSurface = Color(0xFFE0E3E1),
            surfaceVariant = Color(0xFF3F4947),
            onSurfaceVariant = Color(0xFFBEC9C7),
            surfaceTint = Color(0xFF4EEFCE),
            inverseSurface = Color(0xFFE0E3E1),
            inverseOnSurface = Color(0xFF191C1B),
            outline = Color(0xFF889391),
            outlineVariant = Color(0xFF3F4947),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFF404846),
            surfaceDim = Color(0xFF191C1B),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            surfaceContainerLowest = Color(0xFF0E1412),
            surfaceContainerLow = Color(0xFF202524),
            surfaceContainer = Color(0xFF242928),
            surfaceContainerHigh = Color(0xFF2F3433),
            surfaceContainerHighest = Color(0xFF3A3F3E),
            primaryFixed = Color(0xFF73F7E5),
            primaryFixedDim = Color(0xFF4EEFCE),
            onPrimaryFixed = Color(0xFF00201C),
            onPrimaryFixedVariant = Color(0xFF005047),
            secondaryFixed = Color(0xFFCCE8E3),
            secondaryFixedDim = Color(0xFFAFCCBA),
            onSecondaryFixed = Color(0xFF06201D),
            onSecondaryFixedVariant = Color(0xFF334B48),
            tertiaryFixed = Color(0xFFCBE6FF),
            tertiaryFixedDim = Color(0xFFA1CAE7),
            onTertiaryFixed = Color(0xFF001E31),
            onTertiaryFixedVariant = Color(0xFF2C4961),
        )
}
