name: Generate Baseline Profile

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate Baseline Profile
        timeout-minutes: 20
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: google_apis
          arch: x86_64
          profile: pixel_6
          disk-size: 6144M
          ram-size: 3072M
          heap-size: 512M
          show-emulator-log: true
          emulator-boot-timeout: 900
          emulator-options: >
            -no-snapshot-save
            -no-boot-anim
            -noaudio
            -no-window
            -gpu swiftshader_indirect
            -camera-back none
            -no-metrics
          script: ./gradlew :app:generateBaselineProfile || (echo "=== LOGCAT ON FAILURE ===" && adb logcat -d && exit 1)

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update baseline profiles"
          title: "Update Baseline Profiles"
          body: |
            This PR automatically updates the baseline profiles based on the latest performance benchmark run.
          branch: update-baseline-profiles
          delete-branch: true
          # Adjust the path below to match where your profiles are generated
          add-paths: app/src/main/generated/baselineProfiles --info --stacktrace
